### ISSUE TITLE
When will the Github version be released on CRAN?

### ISSUE THREAD

**Issue by zhenglei-gao** [nlmixrdevelopment/RxODE#102]
Dear @mattfidler , is there a plan to submit the Github version to CRAN soon?

I have shared some package/scripts using RxODE but it does not work for my colleague because that the names of the input arguments for `rxSolve` are different from the CRAN version.

The GitHub version uses `ev` instead of `events`, `covs` instead of `iCov`. Also, it is hard to install the GitHub version for a corporate Rstudio Server due to the firewall issues.

**Comment by mattfidler** [comment]
Hi @zhenglei-gao 

There is a CRAN version of RxODE currently that is very close to the github version.  It has `ev` **in addition to** `eventTable` and has dropped `covs` in favor of individual covariates `iCov` which is different in how it is used.

We plan to submit another version soon, but the version on CRAN currently has all the features you list.

**Comment by mattfidler** [comment]
See:

https://cran.r-project.org/web/packages/RxODE/index.html

This is now https://github.com/nlmixrdevelopment/RxODE/tree/v0.9.1-0

**Comment by zhenglei-gao** [comment]
@mattfidler ,  I just realized that the installed version on the corporate server is somehow still ‘0.7.2.5’ even though it is reinstalled by me.   This might due to the company default repository settings. I will check again and close this issue after I solved it.

**Comment by zhenglei-gao** [comment]
The reason is that using Microsoft open R will redirect the repository to  a fixed date per default. Thanks!

**Comment by zhenglei-gao** [comment]
@mattfidler  I am reopening the issue because I realized iCov does not equal to covs in the older version.
There is no further instructions in the current version for how to specify time-varying covariates anymore except mentioning that is should be specified in the eventTable. 
For example, if I have a time varying covariate `Cw` as shown below, how do I achieve the same solution using the current version?    Many thanks!
```
require(RxODE)
message("SDode")
SDode <- RxODE({
  Csi(0) = 0;
  H(0) = 0;
  d/dt(Csi) = kd*(Cw-Csi);
  d/dt(H) = kk*max(Csi-z,0)+hb;
});

 ev <- eventTable(amount.units='mg', time.units='hours')
  tmax  <- 20000
 ev$add.sampling(1:tmax)

sim <- rxSolve(SDode,par,ev,covs=data.frame(Cw=rlnorm(tmax)),covsInterpolation = "constant")
```

**Comment by mattfidler** [comment]
You add the time-varying covariate directly to the event table.  

Since I often use real datasets to do RxODE solving, this is more convenient.  Also it is easier to maintain just one method of time-varying covariate solving:

<details>

``` r
require(RxODE)
#> Loading required package: RxODE
message("SDode")
#> SDode

set.seed(42)
SDode <- RxODE({
  Csi(0) = 0;
  H(0) = 0;
  d/dt(Csi) = kd*(Cw-Csi);
  d/dt(H) = kk*max(Csi-z,0)+hb;
});

ev <- eventTable(amount.units='mg', time.units='hours')
tmax  <- 20000

ev$add.sampling(1:tmax)

## To add a time-varying covariate to the dataset convert the event
## table to a data-frame
ev <- as.data.frame(ev)

## Then add the time-varying covariate
ev$Cw <- rlnorm(tmax);

## Need to add some parameters here
par <- c(hb=1, z=2, kk=3, kd=4)

sim <- rxSolve(SDode,par,ev,covsInterpolation = "constant")

sim %>% plot()
```

![](https://i.imgur.com/MoUOi2H.png)

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

</details>

This should be covered in the covariates documentation website:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-covariates.html

**Comment by mattfidler** [comment]
I know it is inconvenient to have breaking changes, so thank you for your patience.

**Comment by zhenglei-gao** [comment]
I see, I assumed in the beginning `iCov` is `covs` originally but realized the difference when I run the program. 

Sorry for not reading carefully the vignettes which I should have but only glanced through. And thank you for your help!

**Comment by mattfidler** [comment]
No problem.  

I think the new interface is a relatively easy fix. 

The `iCov` allows simulation of individual covariates easier.  That way you don't have to merge them to the dataset.  

Unfortunately the vignette is lagging behind;  The vignette should mention this `iCov` parameter.
