### ISSUE TITLE
use alternative form for backsolve / forwardsolve

### ISSUE THREAD

**Issue by conradsnicta** [nlmixrdevelopment/RxODE#112]
If I haven't misunderstood the intent of the code below, backsolve is indeed available in armadillo. These forms can be used: `X = solve(trimatu(A), B)` or `X = solve(trimatl(A), B)`, or `bool success =  solve(X, trimatu(A), B)`, etc. Recent versions of Armadillo can also determine if the given matrix is symmetric positive definite, and automatically use a dedicated solver.

See the example in the [documentation for solve()](http://arma.sourceforge.net/docs.html#solve).

https://github.com/nlmixrdevelopment/RxODE/blob/cc4cb2136b7b524721177e1530ba430252d19e23/src/cvPost.cpp#L43-L56

**Comment by mattfidler** [comment]
Thanks @conradsnicta  both for your package and your tip.

**Comment by mattfidler** [comment]
Timing before:
```
> microbenchmark::microbenchmark(cvPost(3, matrix(c(1,.3,.3,1),2,2)),times=1000)
Unit: microseconds
                                       expr   min    lq     mean median    uq
 cvPost(3, matrix(c(1, 0.3, 0.3, 1), 2, 2)) 4.195 4.411 5.029422  4.544 4.754
    max neval
 45.676  1000
```

**Comment by mattfidler** [comment]
Timing after:
```R
> microbenchmark::microbenchmark(cvPost(3, matrix(c(1,.3,.3,1),2,2)),times=1000)
Unit: microseconds
                                       expr   min     lq     mean median     uq
 cvPost(3, matrix(c(1, 0.3, 0.3, 1), 2, 2)) 4.002 4.2675 4.804477  4.404 4.6075
     max neval
 325.744  1000
```

**Comment by mattfidler** [comment]
Indeed using `solve()` is faster.

**Comment by mattfidler** [comment]
Thanks again Conrad!
