### ISSUE TITLE
Publish vignettes as html webpages online

### ISSUE THREAD

**Issue by sibojan9** [nlmixrdevelopment/RxODE#137]
In the way, the knowledge of RxODE may spread more easier. This saves the efforts of end-users to knit the RMD file. 

Thanks,

Sibo

**Comment by mattfidler** [comment]
See if this works for you:

https://nlmixrdevelopment.github.io/RxODE/

**Comment by sibojan9** [comment]
That works. I cannot believe that my google search missed these instructions.  Thank you, Matt. - Sibo

**Comment by mattfidler** [comment]
No problem.

**Comment by mattfidler** [comment]
Perhaps I have to submit the site for indexing.

**Comment by sibojan9** [comment]
That would be a good idea.

**Comment by mattfidler** [comment]
Applied for docsearch.

**Comment by mattfidler** [comment]
Also applied for "site" from google;  I'm unsure why but google has not indexed these sites.  They don't appear on my google searches.

**Comment by sibojan9** [comment]
or simply put a link on the GitHub homepage; so everyone can be directed to there.

**Comment by mattfidler** [comment]
It is the first link on the page. It's just hard to see.

**Comment by sibojan9** [comment]
It is indeed hard to see since the tail is truncated. You may mention it again in the end of the instruction.

![image](https://user-images.githubusercontent.com/11802171/68686560-aa270e00-0520-11ea-80b0-17495042e3cb.png)

**Comment by mattfidler** [comment]
Added documentation search.

The readme integrates into the website, so it is a bit odd to have say a website is at X on the website.

In the tidyverse types of applications they don't refer to it;   For example:

https://github.com/tidyverse/stringr

I was thinking of reducing the install instructions a bit or separating it out into its own vignette.  It isn't as important as a quick hit of how to use `RxODE`, I think.  This will take some thought.

**Comment by sibojan9** [comment]
Sounds good.

**Comment by mattfidler** [comment]
Added more reasonable readme.  Still needs work.
