### ISSUE TITLE
Differential equations  

### ISSUE THREAD

**Issue by Mutaz94** [nlmixrdevelopment/RxODE#161]
Hi @mattfidler; a curious question, does RxODE support different DE types and solvers? E.g delay DE , stochastic DE, etc.?

**Comment by mattfidler** [comment]
Hi @Mutaz94. 

`RxODE` dose not support delay DE, stochastic DE or PDE solvers currently.  It is something to consider, but I haven't done anything with that yet.

It does support the following solvers:
- `liblsoda` (which is similar to `mrgsolve`'s new `c++` method).
- `lsoda` the classic fortran solver
- `dop853` algorithm translated to C.

In the development version we have some initial support for inductive linearization from my interpretation of the method by Chihiro Hasegawa and Steve Duffull.

**Comment by mattfidler** [comment]
Note the inductive linearization is equivalent to linear ODE systems using matrix exponentials (which is `ADVAN5/7` in NONMEM)

**Comment by Mutaz94** [comment]
Thank you for the clarification. I noticed the ODE solvers, and it worked well with stiff and non-stiff equations implemented in nlmixr. 
To comment for robust DDE solver, NONMEM ADVAN 16 (Delay DE) (to be released later this year) is implementing this FORTRAN solver [RADAR5](http://www.unige.ch/~hairer/software.html).

**Comment by mattfidler** [comment]
Thank you @Mutaz94 

It is something to consider.  I haven't linked FORTRAN90 to R yet, though I hear it is possible...

I do not know if it is thread safe either.

**Comment by mattfidler** [comment]
I personally do not know why you would use a delay differential equation when you could use a transit compartment model, perhaps I'm missing the picture;  They do similar things, I believe.

**Comment by Mutaz94** [comment]
I agree with you, transit compartments can be done. However, I believe DDEs offer more flexibility in complex dynamic systems with TCMs as mentioned in [Koch et al ](https://link.springer.com/article/10.1007%2Fs10928-014-9368-y)

**Comment by mattfidler** [comment]
I agree.  For now I am focusing on the 80 to 90 percent of models.  It is still something to consider

**Comment by Mutaz94** [comment]
Thanks for the discussion. I'm going to close this issue since another one was opened regarding the issue.
