### ISSUE TITLE
Deactivate active complied model

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#178]
Hello Matt,

I compiled mod1 and called the model with following code in R studio
```r
mod1 <- RxODE(model = ode, modName = "mod1",wd = getwd())
x <- solve(mod1, data, params=params, inits=inits)
```
Now if I change structural model in "ode" and recompile the model still with the name mod1, it seems that mod1 is locked in previous version and not updated in memory (or somewhere else). I cannot delete existing mod1.d folder either. Could you tell me how to deactivate the current model to enable some edits under the same model name? 

One other question: if I use following code to compile model (i.e., no modName or wd argument), where is mod1.d folder (or files in this folder) stored on my computer? 
```r
mod1 <- RxODE({ ... })
```

Thank you!

Rui

**Comment by mattfidler** [comment]
Hi @lirui0321 

> it seems that mod1 is locked in previous version and not updated in memory (or somewhere else). I cannot delete existing mod1.d folder either. Could you tell me how to deactivate the current model to enable some edits under the same model name?

I try to test so the behavior above doesn't occur.  Sometimes if you are restoring your workspace or using the RxODE model in another process this occurs; The tests are currently [here](https://github.com/nlmixrdevelopment/RxODE/blob/master/tests/testthat/test-load.R)

Can you provide a reproducible minimal example so I can figure out what is going on in this case?

> if I use following code to compile model (i.e., no modName or wd argument), where is mod1.d folder (or files in this folder) stored on my computer?

This depends;  If you set the option `options(RxODE.cache.directory="~/.rxCache")` it will store the files in the directory you specify, in this case `~/.rxCache`

Once compiled you can always see what the `C` code and where it is with the `rxC` command:

``` r
library(RxODE)

SDode <- RxODE({
  Csi(0) = 0;
  H(0) = 0;
  d/dt(Csi) = kd*(Cw-Csi);
  d/dt(H) = kk*max(Csi-z,0)+hb;
});

rxC(SDode)
#> C File: /tmp/RtmpGFXAIC/.rxCache/rx_2657a250d3a367868b221d2e652bf701__.rxd/rx_2657a250d3a367868b221d2e652bf701_.c  (summary for code)
```

<sup>Created on 2020-03-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

You can see on my `linux` system it is in the temporary file storage.  This is true of windows and mac as well.  There is some CRAN checks to try to make sure you only write to the temporary R directory (though this is supposed to change in R 4.0).  CRAN wants the user wants to change where things are stored manually or store them in the temporary folder.


For your information the directory has `Makevars` have the `.c`, `Makevars` and `.so` (equivalent to `.dll` files) in it

```sh
Makevars				rx_2657a250d3a367868b221d2e652bf701_.o
rx_2657a250d3a367868b221d2e652bf701_.c	rx_2657a250d3a367868b221d2e652bf701_.so

**Comment by lirui0321** [comment]
Hi Matt,

Thank you very much! Here is the code I used. Basically, it is changing your example three compartment PKPD to a two compartment model. The second model cannot be compiled correctly. In addition, I cannot delete mod1.d folder until I close R studio. R studio shows a warning box "access denied". I have attached a video clip as well (somehow it does not show Rstudio warning box).
 
[RStudio 2020-03-06 14-04-39.zip](https://github.com/nlmixrdevelopment/RxODE/files/4299940/RStudio.2020-03-06.14-04-39.zip)


```R

# Load RxODE
library(RxODE)

# Define model
ode <- "
   C2 = centr/V2;	
   C3 = peri/V3;
   d/dt(depot) = -KA*depot;
   d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
   d/dt(peri) = Q*C2 - Q*C3;
   d/dt(eff) = Kin*(1-C2/(EC50+C2)) - Kout*eff;
"
# Compile model
mod1 <- RxODE(model = ode, modName = "mod1")

# Define system parameters
params <- 
  c(KA = 0.3, CL = 7,             # central 
    V2 = 4.0E+01, Q = 1.0E+01, V3 = 3E+02, # peripheral
    Kin = .2, Kout = .2, EC50 = 8)              # effects
inits <- c(0, 0, 0, 1)   

# Initialize event table
ev <- eventTable()

# Specify dose
ev$add.dosing(dose = 10000, nbr.doses = 1)

# Specify sampling
ev$add.sampling(0:240)

# Simulate
x <- mod1$run(params, ev, inits)


#########################################

# Define model
ode <- "
   C2 = centr/V2;	
   d/dt(depot) = -KA*depot;
   d/dt(centr) = KA*depot - CL*C2;
   d/dt(eff) = Kin*(1-C2/(EC50+C2)) - Kout*eff;
"
# Compile model
mod1 <- RxODE(model = ode, modName = "mod1")

# Define system parameters
params <- 
  c(KA = 0.3, CL = 7,             # central 
    V2 = 4.0E+01,  # peripheral
    Kin = .2, Kout = .2, EC50 = 8)              # effects
inits <- c(0, 0, 0, 1)   

# Initialize event table
ev <- eventTable()

# Specify dose
ev$add.dosing(dose = 10000, nbr.doses = 1)

# Specify sampling
ev$add.sampling(0:240)

# Simulate
x <- mod1$run(params, ev, inits)
```

**Comment by mattfidler** [comment]
Thanks @lirui0321 

I can reproduce it;  I will fix it soon.

**Comment by mattfidler** [comment]
Should be fixed.

**Comment by lirui0321** [comment]
Thank you, Matt! Should I just update my RxODE package?
Rui

**Comment by mattfidler** [comment]
Yes using:

```R
devtools::install_github("nlmixrdevelopment/RxODE")
```

**Comment by mattfidler** [comment]
We will post a new version to CRAN soon.

**Comment by lirui0321** [comment]
Hi Matt,

I am still facing the same issue after using ```r devtools::install_github("nlmixrdevelopment/RxODE") ```

**Comment by mattfidler** [comment]
It apparently only worked on linux.

**Comment by mattfidler** [comment]
Not it seems to work on linux and windows, not mac.

**Comment by mattfidler** [comment]
```sh
══ testthat results  ═══════════════════════════════════════════════════════════
[ OK: 4473 | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ]
1. Failure: (unknown) (@test-issue-178.R#27) 
```

**Comment by mattfidler** [comment]
After manual testing on mac, it seemed to work on the Mac as well....

I will simply disable the test except on Windows and Linux for now.

**Comment by mattfidler** [comment]
This seems to work for me on linux and windows

**Comment by mattfidler** [comment]
You can update and try again with

```{r}
devtools::install_github("nlmixrdevelopment/RxODE")
```

**Comment by lirui0321** [comment]
Hi Matt,

I am still getting the same error. I am using a windows 10 system. R is installed with NLMIXR. 

It seems that the input ode has been updated, but the compiled model is not. 

```r
mod1[[".model"]]
______________________________ RxODE Model Syntax ______________________________
RxODE({
    C2 = centr/V2
    d/dt(depot) = -KA * depot
    d/dt(centr) = KA * depot - CL * C2
    d/dt(eff) = Kin * (1 - C2/(EC50 + C2)) - Kout * eff
}) 
________________________________________________________________________________
> mod1[[".mv"]][["model"]]
                                                                                                                                                    normModel 
"C2=centr/V2;\nC3=peri/V3;\nd/dt(depot)=-KA*depot;\nd/dt(centr)=KA*depot-CL*C2-Q*C2+Q*C3;\nd/dt(peri)=Q*C2-Q*C3;\nd/dt(eff)=Kin*(1-C2/(EC50+C2))-Kout*eff;\n" 
```

**Comment by mattfidler** [comment]
Hm.  For a work-around you can use `rxDelete(mod1)`

``` r
# Load RxODE
library(RxODE)

# Define model
ode <- "
   C2 = centr/V2;   
   C3 = peri/V3;
   d/dt(depot) = -KA*depot;
   d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
   d/dt(peri) = Q*C2 - Q*C3;
   d/dt(eff) = Kin*(1-C2/(EC50+C2)) - Kout*eff;
"
# Compile model
mod1 <- RxODE(model = ode, modName = "mod1")

# Define system parameters
params <- 
  c(KA = 0.3, CL = 7,             # central 
    V2 = 4.0E+01, Q = 1.0E+01, V3 = 3E+02, # peripheral
    Kin = .2, Kout = .2, EC50 = 8)              # effects
inits <- c(0, 0, 0, 1)   

# Initialize event table
ev <- eventTable()

# Specify dose
ev$add.dosing(dose = 10000, nbr.doses = 1)

# Specify sampling
ev$add.sampling(0:240)

# Simulate
x <- mod1$run(params, ev, inits)
#> Warning in rxSolve_(object, .ctl, .nms, .xtra, params, events, inits, setupOnly
#> = .setupOnly): Assumed order of inputs: depot, centr, peri, eff


#########################################
rxDelete(mod1)
#> [1] TRUE
# Define model
ode <- "
   C2 = centr/V2;   
   d/dt(depot) = -KA*depot;
   d/dt(centr) = KA*depot - CL*C2;
   d/dt(eff) = Kin*(1-C2/(EC50+C2)) - Kout*eff;
"
# Compile model
mod1 <- RxODE(model = ode, modName = "mod1")

# Define system parameters
params <- 
  c(KA = 0.3, CL = 7,             # central 
    V2 = 4.0E+01,  # peripheral
    Kin = .2, Kout = .2, EC50 = 8)              # effects
inits <- c(0, 0, 1)   

# Initialize event table
ev <- eventTable()

# Specify dose
ev$add.dosing(dose = 10000, nbr.doses = 1)

# Specify sampling
ev$add.sampling(0:240)

# Simulate
x <- mod1$run(params, ev, inits)
#> Warning in rxSolve_(object, .ctl, .nms, .xtra, params, events, inits, setupOnly
#> = .setupOnly): Assumed order of inputs: depot, centr, eff
```

<sup>Created on 2020-03-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I will see what I can do

**Comment by lirui0321** [comment]
Many thanks, Matt! It works now.

Rui

**Comment by mattfidler** [comment]
Great!
