### ISSUE TITLE
Lower incomplete gamma function

### ISSUE THREAD

**Issue by levenc** [nlmixrdevelopment/RxODE#185]
Hello,
I'm trying to implement a gamma absorption model associated with exponential elimination (as seen [here](https://doi.org/10.2165/00003088-200140050-00004) and [here](https://doi.org/10.1007/s40262-017-0533-5)) with nlmixr.
I use the product of the gamma distribution function (pgamma() in R) and the gamma function to define the lower incomplete gamma function, but executing nlmixr returns an error : 

```
> fit <- nlmixr(f, rosco_data, est="focei")
Calculate ETA-based prediction and error derivatives:
Load into sympy...
Error in pgamma(((b - alpha) * t), a, b, TRUE, FALSE) : 
  RxODE doesn't know how to translate 'pgamma' to SymPy.
```

SymPy has the [lowergamma function](https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.gamma_functions.lowergamma), which directly provides the lower incomplete gamma function, but I don't know if it is possible to call it directly from R/RxODE. My model is the following: 

```
f <- function(){ 
  ini({
    ## Initial conditions for population parameters
    la <- log(5.0)      #log a (gamma distribution shape parameter)
    lb <- log(50.0)     #log b (gamma distribution rate parameter)
    lalpha <- log(0.1)  #log alpha (elimination parameter)
    prop.err <- c(0.2)
    
    ## Initial estimate for IIV variance
    eta.a ~ 0.1        #BSV a
    eta.b ~ 0.1        #BSV b    
    eta.alpha ~ 0.1    #BSV alpha
  })

  model({
    a <- exp(la + eta.a)
    b <- exp(lb + eta.b)
    alpha <- exp(lalpha + eta.alpha)

    #lower incomplete gamma as a product of gamma CDF and gamma function
    inc_gamma<-pgamma(((b-alpha)*time),a,b,TRUE,FALSE)*gamma(a) 

    #convolution product of gamma absorption and monoexponential elimination
    c_centr<-AMT*((b/(b-alpha))^a)*inc_gamma*exp(-alpha*time)
    
    c_centr ~ prop(prop.err)
    
  })
}

```

To get around the problem I considered using the [source of the gammainc.R package](https://rdrr.io/cran/pracma/src/R/gammainc.R) but it doesn't seem possible to define a function in the model. It also doesn't seem possible to use a for loop in the model.
Is there a way to implement an incomplete gamma function in nlmixr? If needed, I can send a sample of the data I want to model by email.
Sincerely

**Comment by mattfidler** [comment]
Boost may work;  I will have to figure out if it is thread safe.

Right now, I will focus on making the symengine branch stable so you could use that. See Issue #170 

If you are inclined you can fork the repository from that branch and try to add the function to `RxODE` now

**Comment by levenc** [comment]
Thanks. According to `boost` documentation, all the functions belonging to `math` are thread safe : https://www.boost.org/doc/libs/1_72_0/libs/math/doc/html/math_toolkit/threads.html

I'll probably have a lot of source code reading to do first, but I'll try to add the command after forking this branch as you suggest.

**Comment by mattfidler** [comment]
Ok. To help, here is the process:
1. Adding a Cpp file with the function in `src/lowergamma.cpp` or some other file name
2. Adding a C type export (so it can available to models)
3. Adding the cpp file to the `src/Makevars`
4. Add the C export to the R/C interface `src/init.c`.  Here you have to declare the function and then export it using `R_RegisterCCallable("RxODE", "lowergamma", (DL_FUNC) lowergamma)`
5. Create a typedef and function for the lowergamma in `inst/include/RxODE_model.h`
6. Add the typedef and register the function for the compiled model in `inst/include/RxODE_model_shared.h`  For example: `lowergamma =(lowergamma_p)R_GetCCallable("RxODE", "lowegamma");`
7. Create a RxODE model that makes sure that lowergamma is working and then add it to the testing scripts.
8.  Add your name as a contributor to `RxODE` in the description.

For the last two steps you can use the `linCmtA` or `linCmtB` as examples.

If it seems too much, I will try to get to it after stablizing nlmixr/RxODE in these branches.

**Comment by mattfidler** [comment]
Started adding here e9b11232

**Comment by mattfidler** [comment]
This is added to the branch.  I noted in testing that `boost`'s version of `gammap` is not as forgiving as `pracma`'s version of `gammap`.
