### ISSUE TITLE
Non-negative ODE Solution

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#188]
Hi Matt,

I have a quick question. Dose RxODE provide an option to constrain the solution of an ODE to be non-negative? or is there a trick that I can use? Thank you!

Rui

**Comment by mattfidler** [comment]
Hi @lirui0321 

There is an option, though I suggest fixing the ODE itself instead of using this option;  From the documentation of `rxSolve` you can see all the options:

> `stateTrim`	
>When amounts/concentrations in one of the states are above this value, trim them to be this value. By default Inf. Also trims to -stateTrim for large negative amounts/concentrations. If you want to trim between a range say 'c(0, 2000000)' you may specify 2 values with a lower and upper range to make sure all state values are in the reasonable range.

If you system is going negative however, the ODE system is likely mis-specified.

**Comment by lirui0321** [comment]
Thank you, Matt! I completely agree with you on that I should try to avoid this option. I have a very stiff equation like d A_undissolved/dt = - ( Solubility - A_dissolved ) * A_undissolved * rate. The model is over-parameterized. When the optimizer looks for optimal, it occasionally tries some large parameter values, making the whole equation very stiff.

**Comment by mattfidler** [comment]
Hopefully this works for you.  We also have some optimizing routines in `nlmixr`.
