### ISSUE TITLE
modeling zero order reaction

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#191]
Hi Matt,

I'd like to include zero order reaction in my ODE model, e.g., d/dt(A) = - k . 

Since I have two zero-order processes, I guess event table for infusion probably won't work, so I tried 
```r
d/dt(A) = - k1 * (A > 0 )
d/dt(B) = k1 * (A > 0 ) - k2 * (B > 0)
```
and
```r
if (A <= 0 ) {k1 = 0}
if (B <= 0 ) {k2 = 0}
d/dt(A) = - k1 
d/dt(B) = k1  - k2
```
However, neither one works. Could you tell me if there is a way to model zero order process? Thank you!

Rui

**Comment by mattfidler** [comment]
Yes, you can model rate directly in `RxODE`;  It uses the `NONMEM` method, `rate=-1` for modeled rate and `rate=-2` for modeled duration. 

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html#modeled-rate-and-duration-of-infusion

**Comment by lirui0321** [comment]
Many thanks, Matt! 
If I have two different rates in the same compartment, for example, one positive rate and a negative rate, should I write ODE as 
```r
rate(depot) = rate_1
rate(depot) = - rate_2
```

**Comment by mattfidler** [comment]
Probably something like:
```{r}
rate(depot) = abs(rate_1 - rate_2)
```

**Comment by mattfidler** [comment]
I'm unsure what a negative zero order rate means, hence the `abs()` protection.

**Comment by lirui0321** [comment]
Thank you,  Matt! I just figured out that I asked a stupid question in my second post: the two rates are additive. So I came to edit it before it wasted your time, but I was late 😀

**Comment by mattfidler** [comment]
Great @lirui0321 

Please reach out if you have any other issues.
