### ISSUE TITLE
inconsistent instruction about negative compartment number

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#193]
Hi Matt,

Just a quick note for you. In your instruction about functions, you mentioned that negative compartment was not allowed [https://nlmixrdevelopment.github.io/RxODE/reference/et.html](https://nlmixrdevelopment.github.io/RxODE/reference/et.html) However, I find that it is actually available as mentioned here [https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html?q=reset#turning-off-compartments](https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html?q=reset#turning-off-compartments).

**Comment by mattfidler** [comment]
Thank you @lirui0321 !!!

**Comment by mattfidler** [comment]
If you are interested you can run the upcoming RxODE interactive tutorial:
```{r}
# install.packages("learnr") # if needed
learnr::run_tutorial("RxODE00syntax", "RxODE")
learnr::run_tutorial("RxODE01events", "RxODE")
```

There will be more interactive tutorials, but I haven't quite updated the documentation (and sometimes it goes out of sync).

**Comment by mattfidler** [comment]
These will be built into Rstudio 1.3 when it is released.

**Comment by mattfidler** [comment]
Should be fixed.

**Comment by lirui0321** [comment]
Thank you, Matt! It would be nice if on one day you can summary all these tricks into a book. This is a very nice package. Although the package seems to start as a R version NONMEM, I feel at this time, it is even more powerful than NONMEM in some features. I am also wondering if you can include a MCMC optimizer to better quantify the uncertainty for the slightly over-parameterized model.

**Comment by mattfidler** [comment]
We have `focei` (including a post-hoc estimation engine) and `saem` optimizes for `nlmixr`

For a model without between subject variability we have a `dynmodel.mcmc` for `mcmc` estimation.

**Comment by mattfidler** [comment]
A cheat sheet would be helpful and a full manual;  I haven't written one yet.  

There are many new features that are coming as well that are on the development branch.

**Comment by lirui0321** [comment]
Hi Matt,
Thank you very much! Once the new features become available, how can I know that? Is there a page publishing new features?

**Comment by mattfidler** [comment]
Yes.  

https://nlmixrdevelopment.github.io/RxODE/News.html

**Comment by mattfidler** [comment]
And

https://github.com/nlmixrdevelopment/RxODE/releases
