### ISSUE TITLE
Question: Is it possible to fit a naive pooled (fixed-effect only) model?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#215]
I have some nonclinical data with one observation per animal that I want to fit.  Is it possible to fit a naive pooled, fixed-effects only model with nlmixr?  (I realize that it goes against the "mix" part of the name of the package.)

**Comment by mattfidler** [comment]
Yes.  Using `"dynmodel"`;  The branch you are using has partial support for `est="dynmodel"`

Last year our summer intern Mason McComb and I expanded Wenping's `dynomdel` and integrated it into nlmixr's `UI` some functionality for this.  I was testing it and found it didn't support all the features I thought it did (he may have forgot to commit a piece of code).

The cleanup of `dynmodel` is on my todo list

**Comment by mattfidler** [comment]
Yes now using "focei" without random effects.

**Comment by billdenney** [comment]
Thank you!
