### ISSUE TITLE
Feature Request: Allow the `id` column to be a character or factor like `cmt`

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#217]
This is not high priority for my immediate needs.  :)

As documented in https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html, the `id` column must be an integer >0, sorted.

The `cmt` column is more flexible in that it can be an integer, a character string, or a factor.  It would be helpful if the same logic that applies to `cmt` could be applied to `id` so that, for typical clinical study data, we could use the unique subject identifier (`USUBJID` in SDTM and ADaM CDISC standard) rather than `as.integer(factor(USUBJID))`.

While by itself, there is little benefit to not converting to an integer, the benefit comes for specific subjects that may need to be handled differently in the model (e.g. I know that subject "A123-001" vomited shortly following dosing.  If I could use the USUBJID as the `id`, then I could include a statement in the model like `id("A123-001")` to switch on that subject rather than adding another indicator column to the data for that subject.  (There are other examples like that, too.)

**Comment by mattfidler** [comment]
Actually the documentation is outdated;  It can be anything, but is converted to a factor afterward, so feature request granted.

**Comment by mattfidler** [comment]
It doesn't need to be sorted either.

**Comment by mattfidler** [comment]
However, you cannot refer to `ID=="A123-001"` or for that matter `CMT=='central'` currently.

**Comment by mattfidler** [comment]
So, perhaps feature request partially granted.

**Comment by billdenney** [comment]
:)

My reading of the web page was that I could refer to `CMT == cmt("central")` (which would be good enough for me).  I do think that referring to it as `CMT == "central"` or "ID == "A123-001"` would be simpler for the user, but it seems like the effort to wrap  `cmt("central")` is small enough for the user that there would be no complaint from me.  (For the next long while, anyway. :-P)

**Comment by mattfidler** [comment]
`CMT == cmt("central")` doesn't work either.  

`cmt()` changes the order of the compartments so:

`cmt(depot, central)` will have `depot when CMT=1` and `central when CMT=2`

However, `cmt("central")`  currently does not work either.  I agree in its utility.

**Comment by mattfidler** [comment]
I reread the vignette, and it isn't clear what `cmt()` does, perhaps an example will clarify this;  

Because of the way it reads, `cmt("central")` may be easy enough to implement, though `CMT == "central"` is probably just as much work at this point.

**Comment by billdenney** [comment]
If they're otherwise identical, `CMT == "central"` seems easier from (my) user perspective.

**Comment by mattfidler** [comment]
I agree.  This is my original internal feature request, if you want to track progress of this:

https://github.com/nlmixrdevelopment/RxODE/issues/152

**Comment by mattfidler** [comment]
This is done; 

I am debating of adding a warning(s) when:

- The model tries to compare to a string for a dataset and the input dataset for that variable is not a string/factor.  For example `age=="young"` would warn that `age` is not a string/factor for this input dataset.
- When it is a factor the model would warn when it compares a value that isn't in the input dataest.  For exmaple `age=="red"` would show: `there are no input items where age=="red"`

**Comment by billdenney** [comment]
Great!

I do like the addition of those warnings.  The time that they may be problematic would be in bootstrap, but I assume that they could be suppressed during bootstrap.

**Comment by mattfidler** [comment]
All warnings are suppressed (and can be accessed I think) for the boostrap.
