### ISSUE TITLE
Allow simulation with zero omega/simga matrices.

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#223]
I was able to get around this by setting omega and sigma to be very small:

```
omega <- lotri(eta_ka~1e-8, eta_cl~1e-8)
sigma <- lotri(prop.err~1e-8, add.err~1e-8)
```

So, now that I'm thinking about it, the zero matrix is not positive definite, but perhaps a test for a zero matrix could be added for a fixed-effects-only simulation option?  (This would be similar to the `zero_re()` function in mrgsolve.)

_Originally posted by @billdenney in https://github.com/nlmixrdevelopment/nlmixr/issues/326#issuecomment-649775762_

**Comment by billdenney** [comment]
> Unlike `mrgsolve` the `omega` matrix can specify any parameter in `RxODE`, but with `nlmixr` these are specified. So for `nlmixr` this makes alot of sense

I'm not sure that I understand this statement, but I do see that you have it in hand.  (Thank you!)

**Comment by billdenney** [comment]
With a zero matrix for both omega and sigma, I would suggest that it would be a good idea to indicate as a message to the user (not even a warning) that there is no variability in the simulation and only fixed effects are used.  I assume that it would be uncommon to use them by accident, but info like this wouldn't hurt, IMO.

**Comment by mattfidler** [comment]
In an RxODE model you specify

```r
a <- RxODE({
model1 = par1 + par2
})
```

`par1` could be part of the `omega` matrix, the `sigma` matrix or the fixed effects parameters.  

By naming the `omega` matrix you use, you tell `RxODE` what parameter is a `eta` `theta` or `err` term.

So a message about zero matrix `omega`, `sigma`, etc would still be doable, but I cannot do a `zero_re` like mrgsolve.

**Comment by billdenney** [comment]
Perhaps a simple method to get to `zero_re` could be used from the `nlmixr` side where it is known what parameters are IIV vs residual variability and therefore, one could just do something like `nlmxrSim(..., omega=0, sigma=0)`, and it would make the zero-matrices for you.  (But the first part of it is over here.)

I think that if you get the part working on the RxODE side, I can probably make the contribution on the nlmixr side.  (C++ ain't my skill.)

**Comment by mattfidler** [comment]
Its actually simple on `nlmixr` side.

The code to get to simulation information for any simulations you need is

```r
fit$simInfo
```

With that you can very easily zero out the omegas/sigmas/etc.

**Comment by billdenney** [comment]
I didn't say that I was taking the hard job here.  😉

**Comment by mattfidler** [comment]
This seems to be complete for now:

``` r
library(RxODE)
## Creating covariance matrix

mod <- RxODE({
    eff(0) = 1
    C2 = centr/V2;
    C3 = peri/V3;
    CL =  TCl*exp(eta.Cl) ## This is coded as a variable in the model
    d/dt(depot) =-KA*depot;
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    e = eff+eff.err
    cp = centr*(1+cp.err)
})

ev <- et(amount.units="mg", time.units="hours") %>%
  et(amt=10000, cmt="centr") %>%
  et(0,48, length.out=100)

## Variability  
theta <- c(KA=2.94E-01, TCl=1.86E+01, V2=4.02E+01,  # central 
           Q=1.05E+01, V3=2.97E+02,                # peripheral
           Kin=1, Kout=1, EC50=200)                # effects

omega <- lotri(eta.Cl ~ 0.4^2)
sigma <- lotri(eff.err ~ 0.1, cp.err ~ 0.1)
tmp <- matrix(rnorm(8^2), 8, 8)
tMat <- tcrossprod(tmp, tmp) / (8 ^ 2)
dimnames(tMat) <- list(NULL, names(theta))

sim  <- rxSolve(mod, theta, ev, omega=omega, nSub=100, sigma=sigma, thetaMat=tMat, nStud=10,
                dfSub=10, dfObs=100)

s <-sim %>% confint(c("centr", "eff"))
#> Summarizing data
#> done.

plot(s)
```

![](https://i.imgur.com/vHO1tTh.png)

``` r

omega <- lotri(eta.Cl ~ 0)
sigma <- lotri(eff.err ~ 0, cp.err ~ 0)

tMat <- matrix(0, 8, 8)
dimnames(tMat) <- list(NULL, names(theta))

sim  <- rxSolve(mod, theta, ev, omega=omega, nSub=100, sigma=sigma, thetaMat=tMat, nStud=10,
                dfSub=10, dfObs=100)
#> ℹ zero 'thetaMat' specified, no uncertainty in fixed effects
#> ℹ zero 'omega', no between subject variability
#> ℹ zero 'sigma', no unexplained variability

s <-sim %>% confint(c("centr", "eff"))
#> Summarizing data
#> done.

plot(s)
```

![](https://i.imgur.com/Mnz9ARz.png)

<sup>Created on 2020-06-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by billdenney** [comment]
Thanks!
