### ISSUE TITLE
Concentration drop to zero

### ISSUE THREAD

**Issue by hruehs** [nlmixrdevelopment/RxODE#240]
Hello,
when running a multiple dose simulation by a linear solution of a model I always see a drop to zero concentration a the time point when the second dose is administered (see example below). Not a big issue but I just wanted to share.
  
RxODE({
  ka=1;
  cl=3.5; 
  v2=40; 
  Conc   = linCmt()
  })%>%
  et(dose=100, time=0, addl=6, ii=24)%>% 
  et(0, 250, by=0.1) %>% 
  rxSolve()%>%
  plot()

![grafik](https://user-images.githubusercontent.com/51970790/87288432-a0183d80-c4fb-11ea-89c8-cbde9b763678.png)

**Comment by mattfidler** [comment]
Thank you for reporting this issue;

The entire `linCmt()` was changed in the development version to use the `advan` solutions (as mentioned in #241).

In the development version, this works correctly:

``` r
library(RxODE)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lotri)

RxODE({
ka=1;
cl=3.5;
vc=40;
Conc = linCmt()
})%>%
et(dose=100, time=0, addl=6, ii=24)%>%
et(0, 250, by=0.1) %>%
rxSolve()%>%
plot(Conc)
```

![](https://i.imgur.com/VeC6BLK.png)

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sliao999** [comment]
How can we introduce a absorption lag time in this pk model? in RxODE

Sam Liao

**Comment by mattfidler** [comment]
In theory you simply use `alag(depot)=` but this seems to have the same error as listed above.  I added #258 to track the interaction error.  It may or may not be related to the prior observation.
