### ISSUE TITLE
Keep covariate option confused

### ISSUE THREAD

**Issue by hruehs** [nlmixrdevelopment/RxODE#241]
Hello,
I was simulating a population with individual time changing covariates using the "keep" option when I encountered the following: the covariate presented in the output table is only reflecting the first individual. Nontheless the individual parameters are derrived correctly according to the event table (see figure 1 and table 3). So its not a big deal, but wanted to mention anyway.

```r
library(RxODE)
library(ggplot2)
library(dplyr)
library(lotri)

\# model ----
RxODE({
  tvka=THETA3;
  eta.ka=0
  ka~tvka*exp(eta.ka)
  tvcl=THETA1*cov; 
  eta.cl=0
  cl~tvcl*exp(eta.cl)
  tvv2=THETA2; 
  eta.v2=0
  v2~tvv2*exp(eta.v2)
  IPRED   = linCmt()})->one.comp  

\# parameters ----
thetas<-c(THETA1=1,THETA2=30,THETA3=1)

omega <- lotri(eta.cl ~ 2E-1,
               eta.v2 ~ 3E-2,
               eta.ka ~ 1E-6)

\# event table ----
et(dose=100,addl=6,ii=24)%>%
  et(id=c(1:3))%>%
  et(seq(0,200,.1))%>%
  mutate(cov=1)%>%
  mutate(cov=ifelse(id==1&time>100,1.3,cov))%>%
  mutate(cov=ifelse(id==2&time>110,1.4,cov))%>%
  mutate(cov=ifelse(id==3&time>90,0.9,cov))->ev

\# simulation ----
set.seed(20021988)
one.comp$solve(ev,thetas,omega=omega,keep="cov")%>%
  as.data.frame()%>%
  filter(time==0|IPRED>0)%>%
  mutate(id=factor(id))%>%
  ggplot(aes(x=time,y=IPRED,color=id))+
  geom_line()+
  theme_bw()
```

Figure 1
![grafik](https://user-images.githubusercontent.com/51970790/87294523-32bcda80-c504-11ea-88de-16468ced0224.png)

Table 1
![grafik](https://user-images.githubusercontent.com/51970790/87294812-90512700-c504-11ea-97f9-bb449395308e.png)

Table 2
![grafik](https://user-images.githubusercontent.com/51970790/87294917-bc6ca800-c504-11ea-8631-2921ec0f17c8.png)

Table 3
![grafik](https://user-images.githubusercontent.com/51970790/87294982-d1e1d200-c504-11ea-99e2-5aa682d8b7b7.png)

**Comment by mattfidler** [comment]
Thank you for reporting.  

This has been fixed in the development version of `RxODE`:

``` r
library(RxODE)
library(ggplot2)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(lotri)

# model ----
RxODE({
  tvka=THETA3;
  eta.ka=0
  ka~tvka*exp(eta.ka)
  tvcl=THETA1*cov; 
  eta.cl=0
  cl~tvcl*exp(eta.cl)
  tvv2=THETA2; 
  eta.v2=0
  vc~tvv2*exp(eta.v2)
  cov1 = cov
  IPRED   = linCmt()})->one.comp  

# parameters ----
thetas<-c(THETA1=1,THETA2=30,THETA3=1)

omega <- lotri(eta.cl ~ 2E-1,
               eta.v2 ~ 3E-2,
               eta.ka ~ 1E-6)

# event table ----
et(dose=100,addl=6,ii=24)%>%
  et(id=c(1:3))%>%
  et(seq(0,200,.1))%>%
  mutate(cov=1)%>%
  mutate(cov=ifelse(id==1&time>100,1.3,cov))%>%
  mutate(cov=ifelse(id==2&time>110,1.4,cov))%>%
  mutate(cov=ifelse(id==3&time>90,0.9,cov))->ev

# simulation ----
set.seed(20021988) # note random engine is now threefry, results are different
s <- rxSolve(one.comp, ev, thetas, omega=omega, keep="cov")

plot(s,IPRED)
```

![](https://i.imgur.com/0P4pULf.png)

``` r

print(all(s$cov1==s$cov))
#> [1] TRUE
```

<sup>Created on 2020-07-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
As a work-around you can add the line `cov1=cov` to correctly keep the covariate.

**Comment by mattfidler** [comment]
If you wish, I can give you instructions on how to install the development version of RxODE.

**Comment by mattfidler** [comment]
Also note you are using a time-varying covariate, which gives the incorrect solution using the super-positioning method.  The development version uses the `advan` method which will give the correct solutions.

**Comment by mattfidler** [comment]
I'm sorry; I mis-read your code, each ID has a different covariate, this should be fine. The curves appear different to me, though.
