### ISSUE TITLE
User not warned anymore if Rtools is not installed

### ISSUE THREAD

**Issue by pieterjanvc** [nlmixrdevelopment/RxODE#248]
Hi,

Helping out someone on the Rstudio forum, I discovered that when RxODE is installed with the latest R version, it will not show the correct error message then Rtools is not installed.

Please [see this post for details](https://community.rstudio.com/t/error-in-installing-rxode/74447)

The issue is fixed by installing Rtools, but I think you should check why the error is not displayed correctly (I can see it in the source code, but it's not displayed)

PJ

**Comment by mattfidler** [comment]
Thank you @pieterjanvc 

I hope the new RxODE release will fix this issue.

**Comment by mattfidler** [comment]
Should be fixed.
