### ISSUE TITLE
Time-dependent variable in RxODE

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#252]
Hi Matt,

Is there a way to model time dependent variable in RxODE? For example, something like

An if statement
```r
  rateDepot = 0;    
  if(time>6){  
    rateDepot = 2500;    
  } ;
```

or a weibull function

```r
rateDepot = B * exp(-time^B / A) * (time^B)^(B-1) / A
```

I tried the above code, but run into error. Thank you!

Rui

full code
```r
library(RxODE)

m1 <-RxODE({
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  
  rateDepot = 0;   
  if(time>6){   
    rateDepot = 2500;     
  } ;
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  rate(depot) = rateDepot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, ii=12,until=24, rate=model) %>%
  et(seq(0, 24, length.out=100))

rxSolve(m1, ev) %>% plot(depot, C2) +  xlab("Time")
```

**Comment by mattfidler** [comment]
Yes you can model time dependent variables in `RxODE`, but you cannot model state-dependent `alag()` `rate()` or `dur()`

Here is an example:

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  A=1
  B=0.5
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  rate(depot) = time + 1
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, ii=3,until=24, rate=model) %>%
  et(seq(0, 24, length.out=100))

rxSolve(m1, ev, maxsteps = 7000000) %>% plot(depot, C2) +  xlab("Time")
```

![](https://i.imgur.com/sv7l0aw.png)

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In the case above, the solving didn't occur because `lsoda` couldn't solve the system.

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  A=1
  B=0.5
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  rate(depot) = B * exp(-time^B / A) * (time^B)^(B-1) / A
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, ii=3,until=24, rate=model) %>%
  et(seq(0, 24, length.out=100))

rxSolve(m1, ev, maxsteps = 7000000) %>% plot(depot, C2) +  xlab("Time")
#> Error: could not solve the system
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Which means it is possible with the right ODE system.

**Comment by mattfidler** [comment]
This is using the development version of RxODE

**Comment by lirui0321** [comment]
> This is using the development version of RxODE

Thank you, Matt! I do not think I have the development version on my PC. I installed RxODE with nlmixr's Windows installer. Could you tell me where to download and how to install RxODE development version?

**Comment by mattfidler** [comment]
Instructions are:

https://github.com/nlmixrdevelopment/RxODE/issues/170#issuecomment-598264024

**Comment by lirui0321** [comment]
Many thanks, Matt!

**Comment by lirui0321** [comment]
Hi Matt, I have to bother you again. I coded my rate as a Weibull function of time. As you mentioned, ODE was solved with proper parameter values. However, the simulation does not make sense. My rate starts from zero, and reaches to 3000 at about 3 hour, then decrease to a tiny value within about 10 hours. I am expecting that "depot" amount would reach to about a few thousand within the first a few hours, then start to decrease. Although the simulated depot rate is correct, simulated depot amount (and other amounts) is completely different from my expectation (results attached). 

I am wondering if I still coded it wrong. 

```R
library(RxODE)

m1 <-RxODE({
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  
  A = 3.104
  b = 1.4792
 rateDepot = 10000 * b * exp(-((time)^b)/A) * (time)^(b-1)/A;    
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  rate(depot) = rateDepot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, nbr.doses = 1, rate=-1) %>%
  et(seq(0, 48, length.out=1000))

sim<-rxSolve(m1, ev, maxsteps = 7000000) 
sim %>% plot(depot, C2) +  xlab("Time")
```

![image](https://user-images.githubusercontent.com/61796473/88755469-4042a900-d12f-11ea-908c-33fdca5144db.png)

**Comment by lirui0321** [comment]
I am still using the released rxODE version of 0.9.2-0. Is that the problem?

**Comment by mattfidler** [comment]
Hi @lirui0321 

The rate and duration is calculate *at the time of the infusion* and then doesn't change afterward.

I'm unsure if you want weibull rate, or weibull absorption;  Typically I code weibull absorption as:

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
  KA1=2.94E-01;
  gamma1 = 3
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  
  A = 3.104
  b = 1.4792
  wb  = 1 - exp((-KA1 * time) ^ gamma1)
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-wb*depot;
  d/dt(centr) = wb*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, nbr.doses = 1) %>%
  et(seq(0, 48, length.out=1000))

sim<-rxSolve(m1, ev) 
sim %>% plot(depot, C2) 
```

![](https://i.imgur.com/j7ebNso.png)

<sup>Created on 2020-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

If instead you want the rate to change, you could have a compartment that turns on and off you could use:

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
  ka=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  
  A = 3.104
  b = 1.4792
  C2 = centr/V2;
  C3 = peri/V3;
  A = 3
  B = 2
  d/dt(wb) = -10000*b^2*exp(-time^b/A)*time^(-2 + 2*b)/A^2 + 10000*b*exp(-time^b/A)*(-1 + b)*time^(-2 + b)/A
  d/dt(depot) =-ka*depot + wb;
  d/dt(centr) = ka*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

ev <- et(timeUnits="hr") %>%
  et(amt=10000, nbr.doses = 1) %>%
  et(seq(0, 48, length.out=1000))

sim<-rxSolve(m1, ev) 
sim %>% plot(depot, C2) 
```

![](https://i.imgur.com/XZGxtVQ.png)

<sup>Created on 2020-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Note I took the derivative of your weibull expression with respect to time.  In this case, the time is solved as the whole system is solved.

**Comment by lirui0321** [comment]
Thank you very much, Matt! That's a very smart way to handle it. 

Rui
