### ISSUE TITLE
lag time

### ISSUE THREAD

**Issue by sliao999** [nlmixrdevelopment/RxODE#255]
How can I introduce lag time in absorption process using RxODE?

**Comment by mattfidler** [comment]
Use alag(cmt) =

If it is a solved system the compartments are named depot and central

**Comment by sliao999** [comment]
Thanks for your quick reply! Do I use it inside the ode block like this below?

#Define TMDD SC model
ode <- "
C2=centr/V2;
C3=peri1/V3;
alag(1) = lag1;
TDVM=VMAX*exp(-kdes*t);
d/dt(depot) = -KA*depot;
d/dt(centr)= KA*depot-CL*C2-Q*(C2-C3)-(TDVM*C2)/(KM+C2);
d/dt(peri1) = Q*(C2-C3);
"

Sam Liao

**Comment by mattfidler** [comment]
You use `alag(depot)` instead of `alag(1)`;

Here is an example:

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
m <- RxODE({
  C2=centr/V2
  C3=peri1/V3
  VMAX = 1
  kdes = 0.5
  KA = 0.25
  lag1 = 1
  CL = 10
  KM = 30
  Q = 1
  V3 = 100
  V2 = 10
  TDVM=VMAX*exp(-kdes*t)
  d/dt(depot) = -KA*depot
  alag(depot) = lag1
  d/dt(centr)= KA*depot-CL*C2-Q*(C2-C3)-(TDVM*C2)/(KM+C2)
  d/dt(peri1) = Q*(C2-C3)
})

et <- et() %>%
  et(amt=1000) %>%
  et(0, 72, length.out=100)
  

s <- rxSolve(m, et)

plot(s, log="y")
#> Warning: Transformation introduced infinite values in continuous y-axis
```

![](https://i.imgur.com/F9zdF6u.png)

<sup>Created on 2020-08-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by sliao999** [comment]
Dear Matthew:
Thanks alot. This is very helpful.

Sam Liao
