### ISSUE TITLE
Installing Rtools 

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#276]
Hi Matt,

I just re-installed RxODE. I feel it is important to inform user that they need to Putting Rtools on the PATH. It is mentioned on Rtools website, but if users install rtools through R, then they won't see this.

**Comment by mattfidler** [comment]
I agree. See #248 

It used to check and warn, but with the Rtools 4.0 toolchain it hasn't warned.

**Comment by mattfidler** [comment]
In theory this should be fixed with the new release.
