### ISSUE TITLE
pruneBranch Issues on Linux

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#279]
Related to #278.

While installing `pruneBranch` on Linux, I see the following warning:

```
configure: creating ./config.status
config.status: creating src/Makevars
sh: 0: Can't open inst/tools/stripper/stripper
--------[begin src/Makevars]--------
```

I don't know if it is important-- this is more of an FYI for something that I found while installing in case there were something important to catch.  (I.e. feel free to close if unimportant.)

**Comment by mattfidler** [comment]
It strips debugging symbols from RxODE to try to save install space. 

It likely isn't a problem, and I have disabled/enabled it multiple times.

**Comment by billdenney** [comment]
No worries then.  Thanks for letting me know.
