### ISSUE TITLE
NULL Error after Upgrading RxODE

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#287]
I got the following error after upgrading RxODE:

```
onecmt_iivka 
i parameter labels from comments will be replaced by 'label()'
RxODE model syntax error:
================================================================================
:001: tvKA=THETA[1]
:002: tvCL=THETA[2]
:003: tvVc=THETA[3]
:004: eta_CL=THETA[4]
:005: eta_Vc=THETA[5]
:006: err_add=THETA[6]
:007: err_prop=THETA[7]
:008: eta_KA=ETA[1]
:009: NULL

RxODE syntax error after 'NULL':
:010:     nlmixr_pred <- CP
          ^
:010: CP
================================================================================
 Error in rxModelVars_(obj) : 
  Evaluation error: RxODE syntax error after 'NULL':
:010:     nlmixr_pred <- CP
          ^
more errors could be listed above. 
```

The error was fixed by running `rxClean()` and retrying the model.  I think that the dll was leftover from the previous version of RxODE.  I cannot reproduce the error now (I think because I already cleaned everything up).

Is it possible that the error was due to differing versions of RxODE for DLL compilation?  And, if so, is it possible to check if the current version of RxODE is the same as the version the dll was compiled with and if not, run `rxClean()` automatically?

Edit: One possible way to accomplish this could be simply checking the creation date of the RxODE object files relative to the dll file (rather than adding version information to the dll which was my initial thought).

**Comment by mattfidler** [comment]
In theory the dll has version information but loading with different versions of RxODE have caused crashes.  The caching is a good/bad thing.  With caching you can run things in R-version of parallel processing, but it causes these issues.  I'm unsure if there is a last modified date on all systems to let you know if you have the same cache.  

I suppose the cache could be populated with a single file with the RxODE version and compared.  If compared it will cleanup the cache directory.

By the way  #286 may imply there is a systematic issue in solving that causes `focei` and possibly other algorithms not to perform as well as they did in the past.  I'm still exploring it but the process is slow.

**Comment by mattfidler** [comment]
This should be fixed in the development version of RxODE.  When RxODE detects a version update (through composite md5 hash of key source files), it will run `rxClean` equivalent to alleviate this and other sorts of problems.
