### ISSUE TITLE
RxODE Silently Sorting Times?

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#288]
I have a model where I need to dose a subject make observations, reset the subject, dose again, and make different observations at that new dose level.

In NONMEM, that would involve putting a reset EVID in the dataset between the occasions and no additional sorting would occur.  When I created the dataset for RxODE, I found that all the doses at time 0 were administered at the same time.  It appears that RxODE sorts the data by time within a subject without regard to `EVID == 3`.  (See example below.)

For NONMEM users, this is not the expected behavior.  If this is intended behavior, it would help to have some sort of warning that the data are being sorted.  Is there any way to have the system reset while keeping the integrations separate from before and after the reset event while using the same time definitions starting at zero (as suggested by the `et` dataset below)?

``` r
library(RxODE)
#> RxODE 0.9.2.0 using 4 threads (see ?getRxThreads)
library(tidyverse)

mod1 <-RxODE({
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
});

et_1 <-
  #et(amount.units='mg', time.units='hours') %>%
  et(dose=10000, addl=0, ii=0) %>%
  #et(amt=20000, nbr.doses=5, start.time=120, dosing.interval=24) %>%
  et(0:8)

et_reset <- et(evid=3)

et_2 <-
  #et(amount.units='mg', time.units='hours') %>%
  et(dose=20000, addl=0, ii=0) %>%
  #et(amt=20000, nbr.doses=5, start.time=120, dosing.interval=24) %>%
  et(0:8)

et <- bind_rows(et_1, et_reset, et_2)
et
#>    id low time high       cmt   amt rate ii addl evid ss dur
#> 1   1  NA    0   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 2   1  NA    0   NA (default) 10000    0  0    0    1  0   0
#> 3   1  NA    1   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 4   1  NA    2   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 5   1  NA    3   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 6   1  NA    4   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 7   1  NA    5   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 8   1  NA    6   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 9   1  NA    7   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 10  1  NA    8   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 11  1  NA    0   NA     (obs)    NA    0  0    0    3  0   0
#> 12  1  NA    0   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 13  1  NA    0   NA (default) 20000    0  0    0    1  0   0
#> 14  1  NA    1   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 15  1  NA    2   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 16  1  NA    3   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 17  1  NA    4   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 18  1  NA    5   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 19  1  NA    6   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 20  1  NA    7   NA     (obs)    NA   NA NA   NA    0 NA  NA
#> 21  1  NA    8   NA     (obs)    NA   NA NA   NA    0 NA  NA

x <- rxSolve(mod1, et)
plot(x)
```

![](https://i.imgur.com/Tr6KbpW.png)

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mattfidler** [comment]
Hi @billdenney 

Currently this isn't a possibility;  It would be too much to keep track of in an internal sorting algorithm about when to restart.  

I have never used nonmem's `EVID=3` in this manner (I didn't even known it was a possibility), I'm not sure how common this practice is...?  I think it would go against our internal data standards (though negative times are OK).

**Comment by billdenney** [comment]
Fair that it's too much to keep track of during sorting.  Can a warning be issued that the data were not sorted by ID and TIME, so the data were sorted for you?  That would give a heads-up that it's happening.

I used the NONMEM behavior historically when a subject is in a crossover study and there is no carryover (moderately common) and currently when a subject is in multiple studies (much less common).  Practically, it should only has an effect when using nominal times (which I'm doing this time).

**Comment by mattfidler** [comment]
I don't check to see if the data are sorted before I sort them.  Internally both R and data.table do before sorting the whole sequence (since they both use radix sort they have to get the data range).  I actually don't want to issue a warning here if the data are unsorted.  

However, a waning with an `EVID=3` plus a time zero should be OK.  That way I don't have to add another step to setup.

What do you think?

**Comment by billdenney** [comment]
The way that I think of this as an issue is when EVID=3 and time is non-monotonic.  I don't see a way to only warn when the warning is correct without checking for both EVID and montonicity.  I'll think a bit more.

**Comment by mattfidler** [comment]
I suppose you could have the time internally stored in an ascending sequence based on the reset that is a sequence like `10 0 1` could become `10 11 12` and then when outputting the values it would become `10 0 1` again.  It would require another internal `EVID` to reset the time when outputting it as well as an extra piece to the `etTrans` code.

**Comment by mattfidler** [comment]
It would also require the reset to be to zero and not any other time;  Do you know if you can reset to an arbitrary time in NONMEM?

**Comment by billdenney** [comment]
I have only reset to time zero using NONMEM, but I can imagine wanting to reset to arbitrary times (e.g. starting from predose in two rare disease studies where the same person participates in multiple studies).

**Comment by mattfidler** [comment]
This behaviour implicitly assumes that times are sorted in the "correct" way, which was not previously assumed by RxODE

**Comment by billdenney** [comment]
Is there a way to get the same random effects for a subject with the same initialization values (initial amount in a compartment) with different other effects (e.g. with different doses, different covariates, or with different inter-occasion variability)?  That is the overall goal.

**Comment by mattfidler** [comment]
The `evid=3` as it stands already does this, but it does not reset time.  Therefore any ODE models that use `time` will be affected.

**Comment by mattfidler** [comment]
(Of course IOV is only supported in `RxODE` currently).

The discussion is in the event description for RxODE

**Comment by mattfidler** [comment]
This is more or less fixed.
