### ISSUE TITLE
R Crash

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#300]
After updating to the current RxODE when trying to replicate issue #299, R crashes when running:

```r
model <- nlmixr(object=model_1cmt_fixed, data=d_mod, est="focei", control=foceiControl(outerOpt="bobyqa"))
```

The crash occurs just after the header for parameter estimation is printed ("# | Objective Fun | ", etc.).  Is there a way that I can provide an improved bug report for this?

I did run `rxClean()` to try to ensure that there is not an issue with a cached model object file.

**Comment by billdenney** [comment]
FYI, I made sure that I was current on what I think of as the three main libraries:

```r
remotes::install_github("nlmixrdevelopment/n1qn1c")
remotes::install_github("nlmixrdevelopment/RxODE", ref="pruneBranch")
remotes::install_github("nlmixrdevelopment/nlmixr", ref="foceiDur")
```

**Comment by mattfidler** [comment]
I need a model to run to reproduce this;  If you run with linux, I can give more detailed instructions on how to get a c-back-trace.

**Comment by mattfidler** [comment]
My guess this has to do with #291;  I am rewriting the linCmt solving routines currently and that could cause some problems here.

**Comment by billdenney** [comment]
Is there a known commit that I should back up to for stability?

**Comment by billdenney** [comment]
FYI, the crash also occurs with one of the example models:

```r
library(nlmixr)

one.cmt <- function() {
  ini({
    ## You may label each parameter with a comment
    tka <- 0.45 # Log Ka
    tcl <- 1 # Log Cl
    ## This works with interactive models
    ## You may also label the preceding line with label("label text")
    tv <- 3.45; label("log V")
    ## the label("Label name") works with all models
    eta.ka ~ 0.6
    eta.cl ~ 0.3
    eta.v ~ 0.1
    add.sd <- 0.7
  })
  model({
    ka <- exp(tka + eta.ka)
    cl <- exp(tcl + eta.cl)
    v <- exp(tv + eta.v)
    linCmt() ~ add(add.sd)
  })
}

fit <- nlmixr(one.cmt, theo_sd, est="focei")
```

**Comment by mattfidler** [comment]
Try 8cb7fc9f

**Comment by mattfidler** [comment]
Ok.  I will look into it.

**Comment by mattfidler** [comment]
For me, it still runs;  Perhaps it is platform specific.

**Comment by billdenney** [comment]
I'm compiling now...

**Comment by billdenney** [comment]
```r
remotes::install_github("nlmixrdevelopment/RxODE", ref="8cb7fc9")
```

That fixed the crash.  Thanks!

**Comment by mattfidler** [comment]
Great.  I will leave this open and revisit once `linCmt()` is more stable again.

**Comment by mattfidler** [comment]
Actually looking again, I think the problem is that `devtools` will not install if there is github revision is the same for `nlmixr`.  (since `nlmixr` didn't change, don't install it again).

However since I am working on linear compartment systems, the `RxODE` header and solving structure has changed, and the previous compiled `nlmixr` is invalid and will cause crashes with most if not all models.

Therefore the changes in `RxODE` binary headers cause `nlmixr` to crash.

To overcome this in the future, you could use:

```r
remotes::install_github("nlmixrdevelopment/n1qn1c")
remotes::install_github("nlmixrdevelopment/RxODE", ref="pruneBranch")
remotes::install_github("nlmixrdevelopment/nlmixr", ref="foceiDur", force=TRUE)
```

**Comment by billdenney** [comment]
That (unfortunately) makes sense.  Thanks for tracking it down.

**Comment by mattfidler** [comment]
No problem.
