### ISSUE TITLE
Using RxODE on OpenCPU

### ISSUE THREAD

**Issue by ncpunt** [nlmixrdevelopment/RxODE#309]
I was able to create an RxODE application on shiny. Really great to make apps this way. But what I really want is a Web API wrapper to my R libraries (that use RxODE). Plumber is not really an option (single threaded), but OpenCPU seems to be the way to go.  However, I did not get this to work on OpenCPU. Do you have any experience with this? Please see this thread on Google Groups:

Google Groups: https://groups.google.com/g/opencpu/c/eL0PbqdVBVI
GitHub Repo: https://github.com/ncpunt/cortisol

I keep getting the message "Cannot load RxODE dlls for this model" even if if I precompile the model for linux. 

Best,
Nieko.

P.S. I am aware of this issue: https://github.com/nlmixrdevelopment/RxODE/issues/45

**Comment by mattfidler** [comment]
Hi @ncpunt 

I think `RxODE` was temporarily removed from CRAN;  How did you install RxODE?  If it isn't on CRAN this could be the issue right now.

**Comment by ncpunt** [comment]
I don't RxODE, OpenCPU does that. OpenCPU apps are in fact R packages that are published on GitHub. A special OpenCPU webhook picks up the package with each push to the repo. This architecture allows for continuous integration (DevOps). If the removal of RxODE from CRAN would be the issue, I would have expected different error messages. The current message suggests RxODE is actually running.

**Comment by mattfidler** [comment]
Ok.  That probably means you compiled your model on say ubuntu and it should of been compiled on the opencpu platform.  Linux changes linkage locations for security reasons.  Therefore, you need to compile the `RxODE` model after loading the package.  Another way is to compile the models in the code itself.  `rxUse` isn't terribly mature but it allows models to be included in packages.  In that case, it should work with what you are trying to do.

**Comment by ncpunt** [comment]
Aha! I am developing on windows. I quickly figured out that a windows DLL will not work on linux :-). Therefore, I created the model on Ubuntu (virtual machine). But now you are telling me that a binary compiled on Ubuntu will not work on other distros? I think that ocpu.io is hosted on Ubuntu as well. But I tried other solutions as well. E.g. your shiny approach:

load(file.path("./rx_shiny_data.rda"))
if (!rxDynLoad(mod1)) mod1 <- RxODE(mod1, modName="mod1")

But that also did not work on OpenCPU, while it did work on shiny:

demo: https://medimatics.shinyapps.io/cortisol/

So I am a bit stuck here. And that is a shame because OpenCPU has so much potential. It would allow clients (hospitals) to  integrate R microservices into their EHR.

**Comment by mattfidler** [comment]
I think you can still do it;  All you would need is to have the open CPU compile the RxODE model.  You can do this with `rxUse`

https://github.com/nlmixrdevelopment/rxModels

In particular:

https://github.com/nlmixrdevelopment/rxModels/blob/master/build/models.R

Show how you can integrate everything in your package.  This package will compile against a *specific* version of RxODE but will still compile on OpenCPU.

Until `rxUse` becomes fully automated based on a version of RxODE then this requires another update every-time RxODE models change substantially.

**Comment by mattfidler** [comment]
But since it is compiled when your package is compiled, the model is available to you for use.

**Comment by ncpunt** [comment]
I downloaded the rxModels code and executed build/models.R. That seems to work fine. So, I added a build/model.R file to my project for building my cortisol model (see updated repo). The skeleton looks like this.

library(RxODE)

Cortisol2020 = "... the model c-code ..."

rxUse(Cortisol2020);
rxUse();

devtools::load_all()
devtools::document()
devtools::install()

But I get the following error:

> source('~/OpenCPU/cortisol/build/model.R')
Cortisol2020
√ Setting active project to 'E:/R-Projects/OpenCPU/cortisol'
Error in rxModelVars_(obj) : Not compatible with STRSXP: [type=NULL].
In addition: Warning message:
In obj$package <- NULL : Coercing LHS to a list

Below the full code of the model.

Cortisol2020 = "

  # Standard Equations
  Age  = P01_Age + t / 365.0 / 24.0;
  Bw   = P01_Bw;
  C01_Cu = C01_A / C01_V;
  MW_ALB = 66500;
  MW_CBG = 55000;
  MW_COR = 362.46;
  F   = C01_Cu   / MW_COR * 1E6;
  TA  = C01_ALB  / MW_ALB * 1E6;
  TC  = C01_CBG  / MW_CBG * 1E6;
  TCI = (1 - C01_RC) * TC;
  TCE = C01_RC * TC;
  KA  = C01_Kca  / MW_ALB * 1E6;
  KCI = C01_Kci  / MW_CBG * 1E6;
  KCE = C01_Kce  / MW_CBG * 1E6;
  TF  = F * (1 + TA / (KA + F) + TCI / (KCI + F) + TCE / (KCE + F));
  C01_fu = F / TF;
  C01_C  = C01_Cu / C01_fu;
  PO_R = PO_k * PO_A;
  ME_k = ME_CL / C01_V;
  ME_R = ME_k * C01_A;
  fu_Var = C01_fu;

  # Differential Equations
  d/dt(C01_A) = (+PO_R) + (-ME_R);
  d/dt(PO_A) = (-PO_R);
  d/dt(AUCU_AUC) = C01_Cu;
  d/dt(AUC_AUC) = C01_C;

"

**Comment by mattfidler** [comment]
Hi @ncpunt 

This `rxUse` is considered beta still;  However, the process is:
1. Create the compiled model that is `RxODE(Cortisol2020)`
2. Use `rxUse(Cortisol2020)`
3. Use `rxUse()`
4. Add `LinkingTo: RxODE` in the `DESCRIPTION` file
5. Add the roxygen comment `#' @useDynLib cortisol, .registration=TRUE` to load the cortisol model in your file
6. Use `devtools::document()`
7. Use `devtools::install()`

In theory this will give you the right `dll`.  This is considered alpha and doesn't have any automatic tests yet or any way to link to a version of RxODE that changes header information or linkage information (so watch for breakage).  There may be some models where the name mangling doesn't work correctly either, so... This is currently fragile but may get you over the hurdle for now.

I have added a pull request for you that does this for you.  All you have to do is merge and this should work for you.  If you are interested you can see the difference in code.

**Comment by mattfidler** [comment]
IE,

https://github.com/ncpunt/cortisol/pull/1

I haven't tested any data against this, but please let me know if it is working for you.

**Comment by mattfidler** [comment]
What I would really like is for a source-based package like `cortisol`, you would simply compile the model into a named model, say `cortisolModel` and then use:

```r
rxUse(cortisolModel)
```
And all the required items would be done in the background including having a configure script that will regenerate the models based on an arbitrary version of `RxODE`.  

At that point I would consider this approach stable.

**Comment by ncpunt** [comment]
Thank you so much for your effort. Absolutely great. I merged your changes and pushed to GitHub again for triggering the OpenCPU webhook. I get the following 400 response (full response at the end of this message):

ERROR: dependency ‘RxODE’ is not available for package ‘cortisol’

Does this mean that RxODE is still absent on CRAN?

Rscript failed: Loading config from /usr/lib/opencpu/library/opencpu/config/defaults.conf
Loading config from /etc/opencpu/server.conf
Downloading GitHub repo ncpunt/cortisol@master
Running `R CMD build`...
* checking for file ‘/tmp/ocpu-temp/remotes64c4f2e2eefaa/ncpunt-cortisol-26f94e9/DESCRIPTION’ ... OK
* preparing ‘cortisol’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* checking for LF line-endings in source and make files and shell scripts
* checking for empty or unneeded directories
* building ‘cortisol_1.0.tar.gz’
Installing package into '/usr/local/lib/opencpu/apps/ocpu_github_ncpunt_cortisol_00TMP'
(as 'lib' is unspecified)
ERROR: dependency ‘RxODE’ is not available for package ‘cortisol’
* removing ‘/usr/local/lib/opencpu/apps/ocpu_github_ncpunt_cortisol_00TMP/cortisol’
Error: Failed to install 'cortisol' from GitHub:
  (converted from warning) installation of package '/tmp/ocpu-temp/file64c4f1db1fb7c/cortisol_1.0.tar.gz' had non-zero exit status
Execution halted
In R script: 
  do.call(opencpu:::install_apps_one, list(upgrade = FALSE, repo = "ncpunt/cortisol", ref = "master", 
    lib = "/usr/local/lib/opencpu/apps/ocpu_github_ncpunt_cortisol_00TMP", 
    force = TRUE))

**Comment by mattfidler** [comment]
`RxODE` is not on CRAN yet.  It takes CRAN 1-2 weeks to run the ASAN check they want fixed. (which is ironic since they give you typically 2 weeks to fix the issue)

**Comment by mattfidler** [comment]
See: https://cran-archive.r-project.org/web/checks/2020/2020-10-07_check_results_RxODE.html

**Comment by mattfidler** [comment]
In theory, you can grab the github dependency, correct?  On my ubuntu-based system RxODE installed and ran fine on the latest version of R.

**Comment by ncpunt** [comment]
Sure, I installed it that way on my Ubuntu VM as well. Runs perfectly. But the OpenCPU platform is a blackbox to me. I guess they only rely CRAN.

**Comment by mattfidler** [comment]
Thanks for verifying; I guess we just wait for CRAN to review and send it back/publish it again.

**Comment by ncpunt** [comment]
Is there a way to get notified about this or do I simply have to check https://CRAN.R-project.org/package=RxODE regularly?

**Comment by mattfidler** [comment]
I will let you know when I know.

**Comment by mattfidler** [comment]
I checked today and it is back on CRAN

https://cran.r-project.org/web/packages/RxODE/index.html

**Comment by ncpunt** [comment]
Great!. I am working at a paper right now but I will look at somewhere this week.

**Comment by ncpunt** [comment]
Could not resist to trigger the OpenCPU webhook today. And yes, it works.

Shiny version (R)            :  https://medimatics.shinyapps.io/cortisol/
OpenCPU version (R)     :  https://ncpunt.ocpu.io/cortisol
.NET Core version (C#)  :  ..... (todo)

I will add some benchmark parameters to compare the performance of all 3 implementations.

Thank you very much Matt. I could not have done this myself. I will close the issue.
