### ISSUE TITLE
Error while running mod1<-RxODE(model=ode)

### ISSUE THREAD

**Issue by ms-12345** [nlmixrdevelopment/RxODE#31]
Hi,
I've just started using RxODE and I'm a complete beginner. 

I was running the example code from the CPT tutorial on RxODE. 
This line- mod1 <- RxODE(model = ode)
throws up the following warning-
**Warning message:
running command 'make -f "Makevars" -f "C:/PROGRA~1/R/R-34~1.2/etc/x64/Makeconf" -f "C:/PROGRA~1/R/R-34~1.2/share/make/winshlib.mk" SHLIB="rx_948094f13b2d74fbd6bae1bb2e29ca87_x64.dll" WIN=64 TCLBIN=64 OBJECTS="rx_948094f13b2d74fbd6bae1bb2e29ca87_x64.o"' had status 127** 

and subsequently this error-

**In addition: Warning message:
running command 'C:/PROGRA~1/R/R-34~1.2/bin/R CMD SHLIB rx_948094f13b2d74fbd6bae1bb2e29ca87_x64.c' had status 1**

Any suggestions what could have gone wrong?

My second question was-
How do I incorporate covariates into the DE of the model?
If the dosing information depends on weight or BSA, is there anyway to code that rather than fixing the dose?

I appreciate any help in this matter!

Thank you! :)

**Comment by mattfidler** [comment]
Did you figure this out?

**Comment by ms-12345** [comment]
I did! Thank you :) 
I did not download RTools initially, and once I downloaded it, I still faced the same problem. 
I then tried unchecking the 32 bit part of the RTools installation and that worked. :) 

I have a few more doubts in the model I'm running, will open a new issue for that.

Thank you! :)

**Comment by mattfidler** [comment]
You could also install nlmixr

https://github.com/nlmixrdevelopment/nlmixr/releases

Which installs rxode r rtools python and sympy
