### ISSUE TITLE
Delay dosing

### ISSUE THREAD

**Issue by sfreidy0** [nlmixrdevelopment/RxODE#324]
Hi,

I am having issues when delaying the dose to a different time. I am getting error code that the model can not be solved when i delay the dose to later times. if I do start.time = o, the model is solved and I have no error message. However, if I try to delay the dose to later time I get an error message that the model can not be solved. Please, let me know if I am doing something wrong. @

**Comment by mattfidler** [comment]
Hi @sfreidy0,

Can you provide a reproducible example so I can help you.

One way is to use the model from the RxODE tutorial:
```r
## Model from RxODE tutorial
m1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    ## Added modeled bioavaiblity, duration and rate
    fdepot = 1;
    durDepot = 8;
    rateDepot = 1250;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    f(depot) = fdepot
    dur(depot) = durDepot
    rate(depot) = rateDepot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    eff(0) = 1
})
```

**Comment by sfreidy0** [comment]
Hi,

Thank you for your quick reply.
Below are my codes and my error message after I delay the dosing 7 days. The first code work fine even if I put stat.time = 0. But when I put start.time = 7. I get the error message below.


ev_PK <- eventTable()
ev_PK$add.dosing(dose = 7.046*10^24, nbr.doses = 1, dosing.to<http://dosing.to> = 1)
ev_PK$add.sampling(0:45)
x2_nodelay <- as.data.frame(m1_PK$solve(theta_PK,ev_PK, inits))

x2_nodelay
View(x2_nodelay)
plot(x2_nodelay)
matplot(x2_nodelay[,"C2"], type = "l", xlab = "Time(days)", ylab = "Central conc")
### dosing 7 days after infection
evPK7 <- eventTable()
evPK7$add.dosing(dose = 7.046*10^24, nbr.doses = 1, dosing.to<http://dosing.to> = 1, start.time = 7)
evPK7$add.sampling(0:45)
x2PK7 <- as.data.frame(m1_PK$solve(theta_PK,evPK7, inits))


[cid:image002.png@01D6ADE7.23537150]

Thank you so much for your help!


Best Regards,
Soha Freidy, PharmD
PK/PD fellow, UNC Eshleman School of Pharmacy
& Nuventra Pharma Sciences
Sfreidy0@email.unc.edu

**Comment by mattfidler** [comment]
I'm sorry, I don't see an error message here.  Nor can I reproduce your results with the code you gave me.

Try a `reprex` using the package here: https://github.com/tidyverse/reprex

**Comment by mattfidler** [comment]
Let me know if you figure out a way I can reproduce this issue.
