### ISSUE TITLE
Compile the model once, and use it in future?

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#325]
Hello Matt,

Is it possible for me to compile the model into a standard alone file, save it on my hard drive, and then use it in future so that I do not need to compile it every time? (Something like mex file MATLAB generates. ) 

I see RxODE and rxCompile generate C files and DLL files. However, I cannot figure out how to use these files to perform simulations. Thank you!

Rui

**Comment by mattfidler** [comment]
Hi @lirui0321 

You can use the option `RxODE.cache.directory`; 

This allows you to specify:
`
``r
option(RxODE.cache.directory="cacheDirectory")
```

And all RxODE models will be compiled to this directory and relaoded instead of recompiled if necessary.

I don't know what the `mex` file that you are talking about, but maybe this is works for your needs.

Otherwise, you can compile to a specific directory:

```r

mod <- RxODE({
      a <- 6
      b <- 0.6
      d/dt(intestine) <- -a * intestine
      d/dt(blood) <- a * intestine - b * blood
    }, modName="myModel")
```
And the RxODE will compile to a directory "myModel.d" and reload from there.  Currently there is no check for RxODE versions in this approach, so you will have to delete these directories if you upgrade RxODE

**Comment by lirui0321** [comment]
Hi Matt, Thank you!

I understand that I have C and DLL files in myModel.d folder. I'd like to know how to re-load this compiled model. Once I compile the model, there will be a variable "myModel" classified as "RxODE" in R environment. If I close R and restart it, the variable in the environment will disappear. My understanding is that, even if I have all compiled files in myModel.d folder, I will still need "myModel" as an variable in the environment to load compiled files (is that a correct understanding?). I can save and reload environment variables. However, if I change computer and load environment generated from a different computuer, it will run into errors, because the path information stored in the existing "myModel" variable won't match the current computer. Is there a way to deal with that issue? 

Rui

**Comment by lirui0321** [comment]
Hi Matt,

Here a screen to explain what I mean. I compile the model first. I get the myModel.d folder as well as a a variable containing all the info in R environment (Blue box in attached pic). I will save everything in R environment as an R data file. It works fine when re-load R environment data file on my computer.  The problem comes when I send the compiled myModel.d folder as well as R environment data to my colleague. The path info in the red box is where I store model in my computer.  She cannot load the model properly because, the path in red box won't change, and it is still for my computer not hers. I guess R is confused about where to load the model. 

Rui
![tempsnip](https://user-images.githubusercontent.com/61796473/97825221-121fb880-1c8c-11eb-9150-9aa6edb3e0ac.png)

**Comment by mattfidler** [comment]
This doesn't currently work. But it could be made to work.  Really the models should probably be rolled into their own packages before sharing.  Perhaps I can make a function to do this easily.

**Comment by mattfidler** [comment]
I guess something similar to:

http://pkpdsim.ronkeizer.com/export-model.html

**Comment by lirui0321** [comment]
Yes, Matt, I think something like that would work and be very helpful. A package may be a quick and easy way for model sharing, with people with some modeling background/skill. It probably does not take as much effort as building a Shiny GUI for users, while still protects the model integrity when sharing with others.  (BTW, the Shiny link you have on website is broken: [http://qsp.engr.uga.edu:3838/RxODE/RegimenSimulator](http://qsp.engr.uga.edu:3838/RxODE/RegimenSimulator) )

I see you have an example for including compiled model in package. I have no experience in building R package, so I am still trying to read through your instruction over there. So, yes, I believe that an automated package generation will make life easy for people like me.

**Comment by mattfidler** [comment]
I will have to add the RegimenSimulator to ShinyApps or something similar.  Often `shinyapps.io` or similar have platform dependent issues, but adding the package option will hopefully alleviate this.

**Comment by lirui0321** [comment]
Thank you, Matt! Once you solve the shiny or package issue, I am looking forward to seeing your best practice / guidance for sharing RxODE model. 

With your instruction on website and some other tutorial on Google, I was able to pack my compiled models and additional functions into a package yesterday. In general, it was not as difficult as I thought. However, I think the package option will still be very helpful, if I can make a package by just specifying an option.

**Comment by mattfidler** [comment]
I am glad it works for you in the package.

In the next release there will be a `rxPkg` that allows you to create a package from a group of models.  This is slightly more robust than the last package integration;  It will:

-  Generate all the R/C code you need
- Add a `configure` script that will delete all of your C-based source code (which could be changed), and then regenerate it with `rxUse()`.  This means when CRAN updates `RxODE` if they recompile their dependent sources these will also use the correct versions of the models no matter what was submitted.
- Of course if you are developing your own package you can use `rxUse(...)` to add another model to the package

In the testing script I have a very simple example of this:

```r

    mod <- RxODE({
      a <- 6
      b <- 0.6
      d/dt(intestine) <- -a * intestine
      d/dt(blood) <- a * intestine - b * blood
    })

    obs <- units::set_units(seq(0, 10, by = 1 / 24), "days")

    et <- eventTable(time.units = "days")
    et$add.sampling(obs)
    et$add.dosing(
      dose = 2 / 24, start.time = 0,
      nbr.doses = 10, dosing.interval = 1
    )

    solve1 <- rxSolve(mod, et, returnType = "data.frame")

    mod2 <- mod

    dir <- tempdir()

    rxPkg(mod, mod2, package="rxm", wd=dir)
    unlink(dir, recursive=TRUE)

    rm(list=c("mod", "mod2"))

    expect_error(library(rxm), NA)

    expect_error(mod, NA)
    expect_error(mod2, NA)

    expect_true(inherits(mod, "RxODE"))

    expect_true(inherits(mod2, "RxODE"))

    solve2 <- rxSolve(mod, et, returnType = "data.frame")

    expect_equal(solve1, solve2)

    detach("package:rxm", unload=TRUE)

    remove.packages("rxm")

    expect_error(mod)
    expect_error(mod2)

**Comment by mattfidler** [comment]
If you already created a package, I suggest you add the `configure` options discussed above;  In short the files have:

# configure
```sh
#!/bin/sh
echo "unlink('src', recursive=TRUE);RxODE::rxUse()" > build.R
${R_HOME}/bin/Rscript build.R
rm build.R
```
# configure.win

```r
#!/bin/sh
echo "unlink('src', recursive=TRUE);RxODE::rxUse()" > build.R
${R_HOME}/bin/Rscript build.R
rm build.R
```
# configure.ac
```sh
## dummy autoconf script
```

**Comment by mattfidler** [comment]
I am supposing this will finish the problem you have;  I will close the issue.  If you have anything else feel free to reach out.

**Comment by lirui0321** [comment]
Many thanks, Matt!

**Comment by lirui0321** [comment]
Hi Matt, I have one more question. Even though the model has been complied into package, the user will still need to install Rtools, with version consistent with mine. Is that a correct understanding? I shared my package with my colleague today, and she got a error message. The only thing I can think of is the different version of R and Rtools on her and my computers. 

![Picture1](https://user-images.githubusercontent.com/61796473/98053929-ba0dc100-1e07-11eb-9593-6a977df7c5bd.png)

**Comment by mattfidler** [comment]
In theory, you don't actually need Rtools to run the compiled models.  This issue often comes from how you compile models:

- Make sure you compile using dual-platform (`i386` and `x64`)
- Remove any speed-ups that you have included in (`~/.R/Makevars.win`).  Sometimes these are not compatible between different windows computers.

Let me know if that works.

**Comment by lirui0321** [comment]
Thank you, Matt! I basically just copied the code you provided on RxODE website. I pasted my additional functions into Suppoerting_function.R file generated by use_r(). I have almost no experience with preparing packages. Could you tell me where should I specify the platform? and also where to check if I have any speed-ups that I may included by accident? Thank you!

Rui

```r
package_path  <- file.path(getwd(),"GI.PBPK.v13")
create_package(package_path);

use_gpl3_license("RuiLi")
use_package("RxODE", "LinkingTo")
use_package("RxODE", "Depends") ##  library(RxODE) on load; Can use imports instead.
use_roxygen_md()

use_r("Supporting_functions")

rxUse(mod_13comp)
rxUse(mod_13comp_SingleDose)

##' @importFrom RxODE RxODE
##' @export
RxODE::RxODE

devtools::load_all()
devtools::document()
devtools::install()
```

**Comment by lirui0321** [comment]
We figured out. You are right, Matt. I compiled model with 64 bit R, but she used it with a 32 bit R. Once she switched to 64 bit R, it worked.

**Comment by mattfidler** [comment]
Great!  I'm glad it worked
