### ISSUE TITLE
dMod description accurate

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#338]
@dkaschek is the description of dMod accurate:

>which uses a unique syntax to create "reactions". These reactions create the underlying ODEs and then created c code for a compiled deSolve model.

> In contrast RxODE defines ODE systems at a lower level. RxODE's parsing of the mini-language comes from C, whereas dMod's parsing comes from R.

> Like RxODE, dMod supports symbolic manipulation of ODE systems and calculates forward sensitivities and adjoint sensitivities of systems.

> Unlike RxODE, dMod is not thread-safe since deSolve is not yet thread-safe.

The only thing that you may want to mention is the estimation capabilities,

**Comment by dkaschek** [comment]
The description of dMod is accurate. To mention parameter estimation:

* dMod provides facilities to combine models with observed data and prior knowledge into an objective function perfectly suitable for multiple numerical solvers of optimization problems (especially for derivative-based solvers thanks to the propagated forward sensitivities).

**Comment by mattfidler** [comment]
I will probably mention that in the nlmixr section if that is OK with you.

**Comment by dkaschek** [comment]
Sure. Thanks!

**Comment by mattfidler** [comment]
Great
