### ISSUE TITLE
doing in two cmts in RxODE at the same time

### ISSUE THREAD

**Issue by ftuhin2828** [nlmixrdevelopment/RxODE#346]
I just ran into a problem with RxODE that I can't seem to figure out. Does RxODE allow dosing in two cmts at the same time. I know if I want to dose in cmt3, I can just write "dosng.to =3" and that works just perfect. What if I want to dose in both cmt3 and cmt6 at the same time, do you know what would be the code for it if RxODE has the feature to do it. It would be great help. Thanks.

Fazlur

**Comment by mattfidler** [comment]
Below is an annotated example, let me know if it explains it for you.

``` r
library(RxODE)
#> detected new version of RxODE, cleaning cache
#> RxODE 1.0.0.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    ## Added modeled bioavaiblity, duration and rate
    fdepot = 1;
    durDepot = 8;
    rateDepot = 1250;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    f(depot) = fdepot
    dur(depot) = durDepot
    rate(depot) = rateDepot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    eff(0) = 1
})
#> qs v0.23.4.
#> → creating RxODE include directory
#> → getting R compile options
#> → precompiling headers
#> ✔ done

# Simply administer the doses at the same time; You can use the named
# compartments to make sure it gets to the right place

et <- eventTable()
et$add.dosing(100, dosing.to="depot", start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)
```

![](https://i.imgur.com/6OzXede.png)

``` r

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to="eff", start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)
```

![](https://i.imgur.com/YgBVzgN.png)

``` r


## You can also use the compartment numbers

et <- eventTable()
et$add.dosing(100, dosing.to=1, start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)
```

![](https://i.imgur.com/2RzasWG.png)

``` r

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to=4, start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)
```

![](https://i.imgur.com/Jveicbp.png)

``` r

## Sometimes it is easy to overlook the compartment numbers (I did), you can
## see them by printing the model

## Another possibility is to specify the compartments in the model

m1 <-RxODE({
  cmt(depot)
  cmt(eff)
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  ## Added modeled bioavaiblity, duration and rate
  fdepot = 1;
  durDepot = 8;
  rateDepot = 1250;
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  f(depot) = fdepot
  dur(depot) = durDepot
  rate(depot) = rateDepot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
})

et <- eventTable()
et$add.dosing(100, dosing.to=1, start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)
```

![](https://i.imgur.com/VeBf7uB.png)

``` r

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to=2, start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)
```

![](https://i.imgur.com/LbiGh5K.png)

<sup>Created on 2020-12-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ftuhin2828** [comment]
Hi Matt,
It does. Thanks a lot! 
Fazlur
    On Thursday, December 3, 2020, 01:10:43 AM EST, Matthew Fidler <notifications@github.com> wrote:  
 
 


Below is an annotated example, let me know if it explains it for you.
library(RxODE)
#> detected new version of RxODE, cleaning cache
#> RxODE 1.0.0.0 using 4 threads (see ?getRxThreads)

m1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    ## Added modeled bioavaiblity, duration and rate
    fdepot = 1;
    durDepot = 8;
    rateDepot = 1250;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    f(depot) = fdepot
    dur(depot) = durDepot
    rate(depot) = rateDepot
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    eff(0) = 1
})
#> qs v0.23.4.
#> → creating RxODE include directory
#> → getting R compile options
#> → precompiling headers
#> ✔ done

# Simply administer the doses at the same time; You can use the named
# compartments to make sure it gets to the right place

et <- eventTable()
et$add.dosing(100, dosing.to="depot", start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to="eff", start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)

## You can also use the compartment numbers

et <- eventTable()
et$add.dosing(100, dosing.to=1, start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to=4, start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)

## Sometimes it is easy to overlook the compartment numbers (I did), you can
## see them by printing the model

## Another possibility is to specify the compartments in the model

m1 <-RxODE({
  cmt(depot)
  cmt(eff)
  KA=2.94E-01;
  CL=1.86E+01;
  V2=4.02E+01;
  Q=1.05E+01;
  V3=2.97E+02;
  Kin=1;
  Kout=1;
  EC50=200;
  ## Added modeled bioavaiblity, duration and rate
  fdepot = 1;
  durDepot = 8;
  rateDepot = 1250;
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  f(depot) = fdepot
  dur(depot) = durDepot
  rate(depot) = rateDepot
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  eff(0) = 1
})

et <- eventTable()
et$add.dosing(100, dosing.to=1, start.time=3)
et$add.sampling(seq(0, 24, length.out=20))

s1 <- rxSolve(m1, et)

plot(s1, depot, C2, eff)

# Now add a dose in compartment effect compartment at the same time
et$add.dosing(-3, dosing.to=2, start.time=3)

s2 <- rxSolve(m1, et)

plot(s2, depot, C2, eff)


Created on 2020-12-03 by the reprex package (v0.3.0)

**Comment by mattfidler** [comment]
Great!
