### ISSUE TITLE
Package not vailable on CRAN?

### ISSUE THREAD

**Issue by Yuri05** [nlmixrdevelopment/RxODE#359]
It seems that RxODE cannot be installed from CRAN?
![grafik](https://user-images.githubusercontent.com/25061876/102244343-7923c480-3efc-11eb-8bb4-17291d15a6cd.png)

**Comment by mattfidler** [comment]
You are right.  It was removed, but we are going to be submitting to CRAN again soon.

**Comment by mattfidler** [comment]
You can see it on cran-incoming's dashboard:

https://lockedata.github.io/cransays/articles/dashboard.html

**Comment by Yuri05** [comment]
ok, thank you.
