### ISSUE TITLE
Writing shiny app using RxODE as a solver

### ISSUE THREAD

**Issue by ftuhin2828** [nlmixrdevelopment/RxODE#369]
Hi Matt,

I was trying to write a shiny app for one of my projects using RxODE as a solver. I was using the example in the below link as template. However, when I was trying the run this example app, I am getting this "Error in htmlTemplate: object 'template_dfa' not found". I was wondering if you could help me out with this. Thank you! Fazlur

https://rdrr.io/cran/RxODE/src/R/genShinyApp.template.R

**Comment by mattfidler** [comment]
Hi Fazlur,

I am unsure what you want to do here;  For me I would start with filling out the `ODE.config` something like this:

```r
ODE.config <- list(ode = "\n   C2 = centr/V2;\n   C3 = peri/V3;\n   d/dt(depot) =-KA*depot;\n   d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;\n   d/dt(peri)  =                    Q*C2 - Q*C3;\n   d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;\n   ", 
            params = c(KA = 0.294, CL = 18.6, V2 = 40.2, Q = 10.5, 
                V3 = 297, Kin = 1, Kout = 1, EC50 = 200), inits = c(depot = 0, 
                centr = 0, pari = 0, eff = 1), method = "lsoda", 
            atol = 1e-08, rtol = 1e-06)

genShinyApp.template(appDir = "myapp", ODE.config=ODE.config)

library(shiny)
runApp("myapp")
```

I don't get the same error `template_dfa` not found error; The variable `template_dfa` is not actually found in RxODE, so I'm unsure where your error is coming from.

**Comment by ftuhin2828** [comment]
I just copied your code directly and ran. I am getting the same error. I can't seem to figure out where is the error coming from. Thank you for such a prompt reply. 
![image](https://user-images.githubusercontent.com/35270213/106202996-b8466600-6188-11eb-88a8-e918e821b71e.png)

**Comment by ftuhin2828** [comment]
Hi Matt,

I was able to figure it out. Thank you!

Fazlur

**Comment by mattfidler** [comment]
Great!
