### ISSUE TITLE
 PreciseSums (>= 0.3)

### ISSUE THREAD

**Issue by guiastrennec** [nlmixrdevelopment/RxODE#37]
I am trying to install the github version of RxODE but I get an error that  PreciseSums is installed in version 0.1 (cran version) but 0.3 is required. Is this dependency correct or is there a typo in the DESCRIPTION file?

**Comment by mattfidler** [comment]
This is correct;  The github RxODE allows multi-threaded solving of ODE systems.  This requires the PreciseSums package to be thread safe (otherwise R crashes).

To install the development version of RxODE, you can do the following:

```R
devtools::install_github("nlmixrdevelopment/PreciseSums")
devtools::install_github("nlmixrdevelopment/RxODE")
```
Some of the documentation is slightly out of sync (FYI)

**Comment by guiastrennec** [comment]
Great, thanks for clarifying!

**Comment by mattfidler** [comment]
Thanks @guiastrennec.  And thank you for the xpose package.  I also saw your excellent modelviz package. I think that the modelviz packages could possibly be integrated with RxODE/nlmixr as well.  Have you ever considered using modelviz shiny to build differential equations?

**Comment by guiastrennec** [comment]
Thank you for the feedback @mattfidler. My efforts are currently focused on xpose and to be honnest I have left modelviz on the side for now. In the future, I was thinking to make modelviz an add-on to xpose once it becomes more mature. 

I like the idea of building differential equations from modelviz shiny app (i.e. in the spirit of Berkeley madonna) but I am afraid it would be rather difficult to implement (at least for me) and it might also suffer from several limitations (i.e. non-linearities).

Feel free to contact me if you want to talk more about it (PAGE maybe?)

**Comment by mattfidler** [comment]
I'll be at page.  It will be good to meet you.

**Comment by guiastrennec** [comment]
Great I will see you there then :-)
