### ISSUE TITLE
Combination Therapy Simulations: Transit and First-Order Absorptions 

### ISSUE THREAD

**Issue by krinaj** [nlmixrdevelopment/RxODE#373]
Hello,

I am trying to simulate PK following combination therapy of four TB drugs. First, I was able to fit to one or two parameters well using nlmixr (as well as transit() function). Then, final model codes for all four drugs are combined into one RxODE model as we will want to simulate combined PD effects later on. 

Two of the four drugs have transit compartment absorptions while the other two has first-order absorption. When I try to simulate, I am adding event table as following. 

ev <- et(timeUnits="hours") %>%
et(amt=600, time=0, dosing.to="depotR", addl=5, ii=24) %>% #Rifampicin (has transit() in ODE for depotR)
  et(amt=300, time=0, dosing.to="centI", addl=5, ii=24) %>% #Isoniazid (has transit() in ODE for centI)
  et(amt=1600, time=0, dosing.to="depotP", addl=5, ii=24) %>% #Pyrazinamide first-order abs
  et(amt=1200, time=0, dosing.to="depotE", addl=5, ii=24) %>% #Ethambutol first-order abs
  add.sampling(seq(0, 24*5, by=1))

The model runs transit compartment absorptions for both rifampicin and isoniazid, but seems to be ignoring dosing for the other two drugs that has first-order absorptions. 

Alternatively, is there a way to use amt in model code? In that case, I can try transit compartment coding differently (similar to NONMEM to assign PODO based on conditional statement). Currently, I am getting an error that amt cannot be used in model.

Thanks,
Krina

**Comment by mattfidler** [comment]
Hi @krinaj, 

You can use `amt` in the development versions of `nlmixr` and `RxODE`.  The `transit()` model doesn't have a compartment specific `podo`, so I think this is what needs to be done right now.

**Comment by mattfidler** [comment]
Also the old CRAN `RxODE` doesn't have "sticky" values for calculation;  From the NEWS:



 -  Allow sticky left-handed side of the equation; This means for an observation the left handed values are saved for the next observations and then reassigned to the last calculated value.

    This allows NONMEM-style of calculating parameters like tad:

```r
mod1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    if (!is.na(amt)){
        tdose <- time
    } else {
        tad <- time - tdose
    }
})
```
It is still simpler to use:

```r
mod1 <-RxODE({
    KA=2.94E-01;
    CL=1.86E+01;
    V2=4.02E+01;
    Q=1.05E+01;
    V3=2.97E+02;
    Kin=1;
    Kout=1;
    EC50=200;
    C2 = centr/V2;
    C3 = peri/V3;
    d/dt(depot) =-KA*depot;
    d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
    d/dt(peri)  =                    Q*C2 - Q*C3;
    d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
    tad <- time - tlast
})
```

If the lhs parameters haven't been defined yet, they are `NA`

**Comment by krinaj** [comment]
Thanks, Matt. I think it is time for me to upgrade to development versions
of RxODE and nlmixr.

Thanks again and kind regards,
Krina

**Comment by krinaj** [comment]
Hi Matthew,

I was able to install development versions of nlmixr and RxODe and
everything works very well.

Thanks a,
Krina

**Comment by mattfidler** [comment]
Glad to hear it 😄

**Comment by sliao999** [comment]
Hi Matt,
Where can I get the development versions of nlmixr and RxODe?

Sam

**Comment by mattfidler** [comment]
Hi Sam,

The sticky LHS is now in the CRAN RxODE (FYI)

Matt.
