### ISSUE TITLE
vigenette cannot be built or render due to effectmodels_yyy_calc_lhs not provided by package "effectmodels"

### ISSUE THREAD

**Issue by zhenglei-gao** [nlmixrdevelopment/RxODE#395]
I am using **RxODE** to define ode functions and developed a package of ode functions. The package can be installed and used normally with `rxSolve` in the interactive environment. But if I try to build the vignette or try to use **pkdown** then I encounter the following error. It seems having something to do with the lhs variables in the ODEs. Do you have some idea of the reason? 

```
Quitting from lines 57-72 (ODEmodels.Rmd) 
Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits,  : 
  function 'effectmodels_DEBode_calc_lhs' not provided by package 'effectmodels'
Calls: <Anonymous> ... eval -> rxSolve -> rxSolve.default -> .collectWarnings
Execution halted
```

**Comment by mattfidler** [comment]
Hi @zhenglei-gao 

I do not know why.  I just tried with `rxModels` and a vignette built OK for me.

**Comment by mattfidler** [comment]
Perhaps you are missing something like:

```r
##' @useDynLib rxModels, .registration=TRUE
##' @importFrom RxODE RxODE
```

I also stated that `rxModels` depends on `RxODE`

**Comment by mattfidler** [comment]
I also have deleted the `src` directory and changed the `configure` to build the package C sources, then build the package.

**Comment by mattfidler** [comment]
@zhenglei-gao  did you figure this out?  

If not can you provide more details?

**Comment by mattfidler** [comment]
I am assuming this has been figured out.
