### ISSUE TITLE
model$dll$modVars is not initialised for new 'wd'

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#4]
Package Version 0.6.0

Issue: Sometimes the model will compile, but the 'dll' information will not be read into the 'model' variable. This then results in an error as model$dll$modelVars is NULL.

This seems to be related to whether or not the model 'wd' exists already or not.

This issue came to light as I'm trying to run RxODE within a package test suite (using testthat), and it will run fine standalone, but will fail when building the package with "R CMD check".

```R
suppressPackageStartupMessages({
  library(RxODE)
})

model_text <- "
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  "


params <- data.frame(
  KA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
  Q=1.05E+01,  V3=2.97E+02,              # peripheral
  Kin=1, Kout=1, EC50=200                # effects
)


event_table <- RxODE::eventTable()
event_table$add.dosing(dose=10000, nbr.doses=10, dosing.interval=12)
event_table$add.sampling(0:240)


modName <- paste(sample(LETTERS, 5), collapse="")
model   <- RxODE::RxODE(model = model_text, modName=modName, wd='mytempdir')


res <- model$solve(params = params, events = event_table)
# >> Error in if (transit_abs) { : argument is of length zero

model$dll$modVars
# >> NULL

# But if it is now run a second time, with the directory already existing, 
# it works fine
model   <- RxODE::RxODE(model = model_text, modName=modName, wd='mytempdir')
```

**Comment by mattfidler** [comment]
It seems if you simply create `tempdir` this still doesn't work.

**Comment by mattfidler** [comment]
Fixed in 65213ae

**Comment by coolbutuseless** [comment]
Thanks for the quick reply - Unfortunately, this does not seem to work for my use case.

I've created a github repository of a package skeleton, where RxODE is used within a test

https://github.com/coolbutuseless/RxODEbug

If you run tests on the package, or run the code interactively then it works fine.

```{r}
devtools::test() # This works fine
```

However, if you run this within a package check, then it fails
```{r}
devtools::check(document = FALSE) # this fails.
```

Error output:
```
checking tests ... ERROR
  Running ‘testthat.R’
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Error loading model.
  1: RxODE::RxODE(model_text, modName = modName, wd = "/tmp") at testthat/test-bug.R:39
  2: cmpMgr$compile(force)
  3: rxCompile(.model, .mdir, extraC = .extraC, debug = .debug, modName = .modName, calcJac = .calcJac, 
         calcSens = .calcSens, collapseModel = .collapseModel)
  4: rxCompile.character(.model, .mdir, extraC = .extraC, debug = .debug, modName = .modName, 
         calcJac = .calcJac, calcSens = .calcSens, collapseModel = .collapseModel)
  5: stop("Error loading model.")
  
  testthat results ================================================================
  OK: 0 SKIPPED: 0 FAILED: 1
  1. Error: run_model works (@test-bug.R#39) 
  
  Error: testthat unit tests failed
  Execution halted
```

**Comment by mattfidler** [comment]
I will look at it again.

I created a similar test case:

https://github.com/nlmixrdevelopment/RxODE/blob/master/tests/testthat/test-issue-2.R

It ran through the CRAN Win-builder check fine, and also all the checks on unix/linux.  I'm unsure if I will be able to reproduce your issue now or not.

Please share some information about how you have R setup as well.

**Comment by mattfidler** [comment]
I did reproduce your error.  It seems to work fine in the RxODE `check()` but not in your external package's `check()`

**Comment by mattfidler** [comment]
It seems that it is this issue:

https://github.com/r-lib/testthat/issues/144

Adding the following to your `test/testthat.R`
```R
Sys.setenv("R_TESTS" = "")
```
causes your test to run correctly....

**Comment by mattfidler** [comment]
I don't think this is an RxODE issue at this point, rather a testthat issue.

**Comment by coolbutuseless** [comment]
Adding that Sys.setenv() worked for me. Thanks for your help.

**Comment by mattfidler** [comment]
Great!
