### ISSUE TITLE
Feature Request: Clarify "empty data" error

### ISSUE THREAD

**Issue by billdenney** [nlmixrdevelopment/RxODE#412]
When running `nlmixrSim()` just now, I accidentally provided a zero-row data.frame for the `events` argument.  I got an error of `"empty data"` which didn't immediately take me to the fact that my events table was zero-row.  Might it be reasonable to update the error below to something like `"empty events table"` or even `"zero rows in events"`.

https://github.com/nlmixrdevelopment/RxODE/blob/346edfe7be78c8998eccbb51b89a36929de84488/src/etTran.cpp#L1590

**Comment by mattfidler** [comment]
Hopefully this is more clear: `no rows in event table or input data`
