### ISSUE TITLE
Can't solve the system

### ISSUE THREAD

**Issue by ftuhin2828** [nlmixrdevelopment/RxODE#413]
Hi,

I am trying to solve a system with 36 ode equations and I am getting the following errors:

unhandled error message: EE:[lsoda] 700000 steps taken before reaching tout

I was wondering if there is a way I could increase no. of steps. Thank you!

Fazlur

**Comment by mattfidler** [comment]
Hi @ftuhin2828 

You can change this with `rxSolve(...,maxsteps=700000)`

All the solving options are here:

https://nlmixrdevelopment.github.io/RxODE-manual/solve.html

**Comment by ftuhin2828** [comment]
Hi Matt,

Got it! Thanks!

Fazlur
