### ISSUE TITLE
Error in RxODE 1.0.9

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#414]
Hi Matt,

R-studio updated my RxODE from 1.0.8 to 1.0.9. After that, I met the following error in loading the library:

```
Error: package or namespace load failed for ‘RxODE’:
 .onLoad failed in loadNamespace() for 'RxODE', details:
  call: NULL
  error: RxODE compiled with PreciseSums '0.4' but PreciseSums '0.3' is loaded
Recompile RxODE with the this version of PreciseSums
In addition: Warning message:
package ‘RxODE’ was built under R version 4.0.5 

```

Is there anyway to fix it? Thank you!

Rui

**Comment by mattfidler** [comment]
First restart R and or your computer.  Then try:

```R
install.packages("PreciseSums")
````

**Comment by lirui0321** [comment]
> First restart R and or your computer. Then try:
> 
> ```r
> install.packages("PreciseSums")
> ```

Thank you, Matt! That helps. I guess Rstudio only updated RxODE but not dependent packages. With V 1.0.9, I got the following message after loading it:

```
  RxODE 1.0.9 using 2 threads (see ?getRxThreads)
  no cache: create with `rxCreateCache()`
```

What does that mean? Thank you!

Rui

**Comment by mattfidler** [comment]
It means by default all solving uses 2 threads in parallel.  

The cache is used to cache model models so RxODE dosen't need to compile them anymore.  It also allows R style parallel processing of `nlmixr`, while not required it does add some features.

**Comment by lirui0321** [comment]
> It means by default all solving uses 2 threads in parallel.
> 
> The cache is used to cache model models so RxODE dosen't need to compile them anymore. It also allows R style parallel processing of `nlmixr`, while not required it does add some features.

That's really sweet. I occasionally use NONMEM with parallel run, but never figure out how it works. For RxODE, how does it work? Does it split all ID into a few groups, and then assign cores to these groups?

**Comment by mattfidler** [comment]
In RxODE, the parallelization is done by each ID.  Since it is sent to the same processor it does not need to slice it into different groups of IDs like NONMEM does.  

Further in nlmixr's saem, the ode sovling time is recoreded and then sorted so that the longest running individuals are solved first.  This reduces the wait time for one thread to finish near the end of a ODE solving iteration.
