### ISSUE TITLE
'omega' must be symmetric

### ISSUE THREAD

**Issue by andersthorsted** [nlmixrdevelopment/RxODE#418]
Hi,

Firstly, thanks a lot for developing, maintaining and expanding this package (and those related).

I have developed a rather big model (NONMEM) and have implemented it in RxODE to perform simulations. I have defined my OMEGA's using lotri: 
```
omega_structure <- lotri(
  eta.MABKA ~ 6.36E-01,
  eta.MABKE + eta.OSMS0 + eta.KCXKE ~ c(
    9.82E-02,
    1.71E-02,  1.17E-01,
    4.44E-02,  9.29E-02,  1.22E-01
    ),
  eta.RBCMCH_HV + eta.RBCMCV_HV + eta.RBCMTT_HV + eta.PRERIN + eta.RBCMTT_dcSSc + eta.RBCMCV_dcSSc + eta.RBCMCH_dcSSc + eta.PREMTT + eta.LIRF + eta.RETMTT + eta.IMRMTT + eta.RETVOL + eta.IMRVOL + eta.EPOS0 + eta.TPOS0 + eta.MEKRIN + eta.PLTMTT + eta.PLTMPV + eta.PREIMX + eta.MEKIMX~ c(
    1.87E-03,
    1.28E-03,  1.19E-03,
   -1.17E-03,  1.47E-04,  4.07E-02,
    2.49E-05, -1.48E-03, -4.36E-02,  5.14E-02,
    3.34E-04,  1.43E-03,  4.20E-02, -4.57E-02,  4.59E-02,
   -1.31E-03, -8.48E-04,  8.73E-03, -8.52E-03,  7.98E-03,  2.73E-03,
   -1.48E-03, -8.05E-04,  1.13E-02, -1.12E-02,  1.08E-02,  3.14E-03,  3.93E-03,
    1.50E-04, -7.00E-05, -1.14E-02,  1.19E-02, -1.18E-02, -2.44E-03, -3.03E-03,  3.38E-03,
   -5.39E-05, -2.18E-03, -4.45E-02,  5.54E-02, -5.11E-02, -8.84E-03, -9.83E-03,  1.54E-02,  3.33E-01,
   -4.75E-04,  7.97E-04,  1.75E-02, -1.79E-02,  1.80E-02,  3.51E-03,  5.19E-03, -3.98E-03,  1.97E-02,  2.17E-02,
    5.30E-04,  1.92E-03,  5.39E-02, -5.57E-02,  5.79E-02,  1.01E-02,  1.41E-02, -1.48E-02, -2.77E-02,  3.39E-02,  8.41E-02,
   -2.64E-05,  3.81E-05,  8.02E-03, -8.59E-03,  8.39E-03,  1.69E-03,  2.08E-03, -2.41E-03, -1.18E-02,  1.85E-03,  9.73E-03,  1.84E-03,
   -4.49E-04, -2.68E-04,  5.82E-03, -5.63E-03,  5.87E-03,  1.58E-03,  1.78E-03, -1.87E-03, -1.51E-02,  5.60E-04,  6.19E-03,  1.39E-03,  1.45E-03,
    5.25E-03, -1.82E-03,  2.88E-02,  1.31E-03,  4.18E-02,  3.94E-03,  6.97E-03, -1.12E-02,  2.37E-03,  1.27E-02,  7.16E-02,  7.96E-03,  7.04E-03,  4.45E-01,
    2.06E-02,  1.17E-02,  1.84E-03, -3.23E-02,  1.67E-02, -4.66E-03, -1.33E-02, -7.06E-03, -1.14E-01, -3.36E-02, -1.39E-02,  9.14E-03,  4.22E-03, -3.94E-02,  8.13E-01,
    1.07E-02,  4.53E-03, -3.37E-02,  2.02E-02, -3.01E-02, -8.70E-03, -1.75E-02,  2.02E-03, -1.11E-01, -6.03E-02, -7.55E-02,  2.33E-03,  3.22E-03, -6.19E-02,  6.24E-01,  6.41E-01,
   -2.63E-03, -5.94E-04,  3.28E-03, -2.73E-03,  3.73E-03,  1.29E-03,  2.81E-03,  8.81E-04,  1.65E-02,  1.38E-02,  1.05E-02, -1.53E-03, -1.01E-03, -6.10E-03, -9.64E-02, -9.49E-02,  3.35E-02,
    2.42E-04,  3.67E-04, -7.32E-04,  7.05E-04, -5.37E-04, -3.52E-04, -2.00E-04,  4.42E-04,  2.76E-03, -1.34E-03, -1.72E-03, -1.23E-04,  4.47E-05, -2.21E-03, -2.76E-02, -2.74E-02,  9.62E-04,  9.44E-03,
    5.26E-05, -2.00E-03, -3.78E-02,  2.88E-02, -4.39E-02, -6.15E-03, -8.59E-03,  1.27E-02,  1.97E-01, -1.38E-02, -5.89E-02, -5.09E-03, -1.03E-02, -9.55E-02,  3.19E-01,  2.92E-01, -7.98E-02, -1.98E-02,  9.55E-01,
    5.23E-03,  6.10E-03,  6.08E-02, -6.18E-02,  7.88E-02,  1.56E-03,  1.20E-02, -1.71E-02, -1.30E-01, -9.89E-03,  7.53E-02,  1.57E-02,  7.26E-03,  2.04E-01,  3.86E-02,  5.97E-02, -8.36E-02,  4.49E-03,  4.35E-01,  1.16E+00
   )
) 
```
However, when I call the simulation `rxSolve(ode_model, ev1, nSub=n, params = theta, omega = omega_structure, iCov = data.frame(POP = 1))` , I get the error: `Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits,  :  'omega' must be symmetric.`

From what I can read, symmetric means that the matrix is equal to its transpose, but if I run `omega_structure == t(omega_structure)` I get all TRUE. Similar if I run `isSymmetric(omega_structure)` or `isSymmetric.matrix(omega_structure)` I get TRUE.

So I am wondering if I am miss-understanding the error message? 

It works fine when I only include the first nine elements of the "big" BLOCK (eta.RBCMCH_HV : eta.LIRF), but adding further elements prompts the error message. I have the latest CRAN version.

**Comment by andersthorsted** [comment]
Hi, 
A colleague took a look. It seems that the large block of the variance-covariance matrix is not positive semi-definite. The nearest positive semi-definite matrix can be calculated with nearPD from 'Matrix' package. Using this as input the simulation runs just fine. 
Perhaps the error message could be improved, since the matrix is indeed symmetrical (it is the lower triangular that is specified).

**Comment by andersthorsted** [comment]
I must have missed that option sorry - where is it documented??

**Comment by mattfidler** [comment]
I mis-spoke, it is in `nlmixr` proper.  

The function is `cholSE()` takes a nearest choloskey decomposition for a no positive definite matrix.  The cholesky decomposition can be used to either get a positive definite matrix or can be used directly in simulations.

The method is different than the nearPD in `matrix`.  I have found sometimes one performs better in estimation than the other, but I haven't seen the reasons.  In general (at least in estimation) it is better if the matrix is positive definite.

Perhaps a simple text about how to correct the matrix (both options) would be sufficient.

**Comment by mattfidler** [comment]
I was looking at the error messages of the most recent RxODE and they were updated:

https://github.com/nlmixrdevelopment/RxODE/blob/483cac28d07fafc379f138a1de988e7ee21a426f/src/cvPost.cpp#L546

I think the error should be close enough to close this issue.

**Comment by mattfidler** [comment]
This is true for omega too 
https://github.com/nlmixrdevelopment/RxODE/blob/483cac28d07fafc379f138a1de988e7ee21a426f/src/cvPost.cpp#L716
