### ISSUE TITLE
RxODE simulation issue with repeated IV infusion

### ISSUE THREAD

**Issue by snailittle** [nlmixrdevelopment/RxODE#420]
I am trying to set up simulation of repeated IV infusion. I tested that IV bolus would work for the given model but the IV infusion (with rate = xx) did not work, and returned NAN concentrations. Can you let me know what was wrong? I recall that for IV infusion the evid should be set differently.  I am not sure how to make the evid take on the different value in add.dosing()

########## the IV bolus simulation which worked #############

Browse[1]> ev2 <- eventTable(amount.units=NA, time.units=NA) %>%
add.dosing(dose=refdose, nbr.doses=ndose, start.time=0, dosing.interval=d_interv, dosing.to=2) %>%
add.sampling(seq(from=0.1, to=max(sim_time),by=0.1));
Browse[1]> head(ev2)
id low time high cmt amt rate ii addl evid ss dur
1 1 NA 0.0 NA 2 1e+05 0 12 13 1 0 0
2 1 NA 0.1 NA NA NA NA NA NA 0 NA NA
3 1 NA 0.2 NA NA NA NA NA NA 0 NA NA
4 1 NA 0.3 NA NA NA NA NA NA 0 NA NA
5 1 NA 0.4 NA NA NA NA NA NA 0 NA NA
6 1 NA 0.5 NA NA NA NA NA NA 0 NA NA
Browse[1]> out2 <- rxSolve(mod2,theta,ev2,omega=omega,nSub=150)
Browse[1]> head(out2)
sim.id time KA CL V2 Q V3 A2 Conc
1 1 0.1 0.5248215 13.45727 69.32623 0 37.73249 1414.725 20.40678
2 1 0.2 0.5248215 13.45727 69.32623 0 37.73249 1387.528 20.01448
3 1 0.3 0.5248215 13.45727 69.32623 0 37.73249 1360.854 19.62971
4 1 0.4 0.5248215 13.45727 69.32623 0 37.73249 1334.692 19.25234
5 1 0.5 0.5248215 13.45727 69.32623 0 37.73249 1309.034 18.88223
6 1 0.6 0.5248215 13.45727 69.32623 0 37.73249 1283.869 18.51923

########## the IV infusion simulation which did not work #############

Browse[1]> ev2 <- eventTable(amount.units=NA, time.units=NA) %>%
add.dosing(dose=refdose, **rate=refdose/inf_dur**, nbr.doses=ndose, start.time=0, dosing.interval=d_interv, dosing.to=2) %>%
add.sampling(seq(from=0.1, to=max(sim_time),by=0.3));
Browse[1]> head(ev2)
id low time high cmt amt rate ii addl evid ss dur
1 1 NA 0.0 NA 2 1e+05 33333.33 12 13 1 0 0
2 1 NA 0.1 NA NA NA NA NA NA 0 NA NA
3 1 NA 0.4 NA NA NA NA NA NA 0 NA NA
4 1 NA 0.7 NA NA NA NA NA NA 0 NA NA
5 1 NA 1.0 NA NA NA NA NA NA 0 NA NA
6 1 NA 1.3 NA NA NA NA NA NA 0 NA NA
Browse[1]> out2 <- rxSolve(mod2,theta,ev2,omega=omega,nSub=150)

Browse[1]> head(out2)
sim.id time KA CL V2 Q V3 A2 Conc
1 1 0.1 1.389065 13.10178 69.30906 0 49.42001 NaN NaN
2 1 0.4 1.389065 13.10178 69.30906 0 49.42001 NaN NaN
3 1 0.7 1.389065 13.10178 69.30906 0 49.42001 NaN NaN
4 1 1.0 1.389065 13.10178 69.30906 0 49.42001 NaN NaN
5 1 1.3 1.389065 13.10178 69.30906 0 49.42001 NaN NaN
6 1 1.6 1.389065 13.10178 69.30906 0 49.42001 NaN NaN

**Comment by mattfidler** [comment]
Hi @snailittle 

I'm unsure exactly what the problem is, but it would help if I could have a model to test against.  If you can make a reproducible example, (like with the package `reprex`) it would be quite helpful to see what is going on here.  

However, there are examples of how to repeat infusion in the website.  For example:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-event-types.html#constant-infusion-in-terms-of-duration-and-rate

Hopefully this is helpful enough to get you started on what you need.  

Often `NaN` is a product of some ODE specification where you divide by zero, take a negative number and other things like that.  I would double check the ODE and the values of parameters to make sure that none of that is occurring if you want to debug this further without submitting the example (I know there is work involved in making a reproducible example without any data that you have in house).  
 
Let me know if you figure it out or if I can be of more help to you.

**Comment by snailittle** [comment]
Hi Matt
Many thanks for the note.  
Here is the code you can use to see if you can reproduce the same error:

mod2 <- RxODE({
  ## the order of variables do not matter, the type of compartmental
  ## model is determined by the parameters specified.
  KA =  TKA*exp(eta.KA)
  CL =  TCL*exp(eta.CL)
  V2 =  TV2*exp(eta.V2)
  Q =  TQ*exp(eta.Q)
  V3 =  TV3*exp(eta.V3)
  A2   = linCmt(KA, CL, V2, Q, V3);
  Conc = A2/V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01, # central
    TQ=0,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1,
                                                  0,0.04,0.04,0.1,
                                                  0,0.02,0.02,0.04,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1,
         0,0.04,0.04,0.1,
         0,0.02,0.02,0.04,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~",
                                deparse1(etacov), ")")))



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)



My outputs are as follows

> x <- mod2 %>%  solve(theta, omega=omega, ev,nsub=4)
> head(x)
   time      KA       CL       V2 Q       V3  A2 Conc
1 0 [h] 1.16794 1.773668 30.77354 0 602.9949   0    0
2 1 [h] 1.16794 1.773668 30.77354 0 602.9949 NaN  NaN
3 2 [h] 1.16794 1.773668 30.77354 0 602.9949 NaN  NaN
4 3 [h] 1.16794 1.773668 30.77354 0 602.9949 NaN  NaN
5 4 [h] 1.16794 1.773668 30.77354 0 602.9949 NaN  NaN
6 5 [h] 1.16794 1.773668 30.77354 0 602.9949 NaN  NaN
> 
> ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
+   add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
+   add.sampling(0:240);
> 
> x <- mod2 %>%  solve(theta, omega=omega, ev2,nsub=4)
> head(x)
   time        KA       CL       V2 Q       V3       A2     Conc
1 0 [h] 0.7000552 1.763235 46.84644 0 270.0986 213.4634 4.556661
2 1 [h] 0.7000552 1.763235 46.84644 0 270.0986 205.5782 4.388343
3 2 [h] 0.7000552 1.763235 46.84644 0 270.0986 197.9844 4.226241
4 3 [h] 0.7000552 1.763235 46.84644 0 270.0986 190.6710 4.070128
5 4 [h] 0.7000552 1.763235 46.84644 0 270.0986 183.6278 3.919781
6 5 [h] 0.7000552 1.763235 46.84644 0 270.0986 176.8448 3.774988
>

**Comment by mattfidler** [comment]
Yes, I can reproduce:

``` r
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  Q =  TQ * exp(eta.Q)
  V3 =  TV3 * exp(eta.V3)
  A2   = linCmt(KA, CL, V2, Q, V3);
  Conc = A2/V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01, # central
    TQ=0,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1,
                                                  0,0.04,0.04,0.1,
                                                  0,0.02,0.02,0.04,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1,
         0,0.04,0.04,0.1,
         0,0.02,0.02,0.04,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~",
                                deparse1(etacov), ")")))



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time        KA       CL       V2 Q      V3  A2 Conc
#> 1 0 [h] 0.8796147 1.809866 42.21216 0 550.746   0    0
#> 2 1 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 3 2 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 4 3 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 5 4 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 6 5 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2 Q       V3       A2      Conc
#> 1 0 [h] 0.8262963 1.138734 29.96948 0 328.6137 333.6728 11.133753
#> 2 1 [h] 0.8262963 1.138734 29.96948 0 328.6137 321.2323 10.718646
#> 3 2 [h] 0.8262963 1.138734 29.96948 0 328.6137 309.2555 10.319016
#> 4 3 [h] 0.8262963 1.138734 29.96948 0 328.6137 297.7254  9.934286
#> 5 4 [h] 0.8262963 1.138734 29.96948 0 328.6137 286.6251  9.563899
#> 6 5 [h] 0.8262963 1.138734 29.96948 0 328.6137 275.9387  9.207322
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

Here you are using Q=0, but the equations that RxODE currently uses requires the parameter to be non-zero; Also you have the concentration defined incorrectly.  I have updated the code so that it produces the correct values:

``` r
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  Q =  TQ * exp(eta.Q)
  V3 =  TV3 * exp(eta.V3)
  Conc = linCmt(KA, CL, V2, Q, V3);
  A2 = Conc * V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01, # central
    TQ=1,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1,
                                                  0,0.04,0.04,0.1,
                                                  0,0.02,0.02,0.04,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1,
         0,0.04,0.04,0.1,
         0,0.02,0.02,0.04,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~",
                                deparse1(etacov), ")")))



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time       KA       CL       V2         Q       V3      Conc       A2
#> 1 0 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008   0.00000    0.000
#> 2 1 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008  39.87928 1938.183
#> 3 2 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008  77.32001 3757.849
#> 4 3 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 112.47281 5466.320
#> 5 4 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 145.47898 7070.461
#> 6 5 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 176.47111 8576.718


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2         Q      V3     Conc        A2
#> 1 0 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 206.9936 10000.000
#> 2 1 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 197.1502  9524.457
#> 3 2 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 187.7837  9071.956
#> 4 3 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 178.8710  8641.378
#> 5 4 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 170.3901  8231.661
#> 6 5 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 162.3201  7841.793
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

If you wish to use a simple 1 compartment model, this will still work but you currently have to drop the Q value.  

``` r
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  #Q =  TQ * exp(eta.Q)
  #V3 =  TV3 * exp(eta.V3)
  Conc = linCmt(KA, CL, V2);
  A2 = Conc * V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01 # central
    #TQ=1,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL~",
                                deparse1(etacov), ")")))
#> Error: number of items and lower triangular matrix mismatch



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time       KA       CL      V2      Conc       A2
#> 1 0 [h] 0.868973 2.141941 39.6459   0.00000    0.000
#> 2 1 [h] 0.868973 2.141941 39.6459  49.10806 1946.933
#> 3 2 [h] 0.868973 2.141941 39.6459  95.63337 3791.471
#> 4 3 [h] 0.868973 2.141941 39.6459 139.71176 5538.998
#> 5 4 [h] 0.868973 2.141941 39.6459 181.47192 7194.617
#> 6 5 [h] 0.868973 2.141941 39.6459 221.03578 8763.161


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2     Conc        A2
#> 1 0 [h] 0.9765872 2.170015 45.00548 222.1952 10000.000
#> 2 1 [h] 0.9765872 2.170015 45.00548 211.7358  9529.273
#> 3 2 [h] 0.9765872 2.170015 45.00548 201.7689  9080.704
#> 4 3 [h] 0.9765872 2.170015 45.00548 192.2711  8653.251
#> 5 4 [h] 0.9765872 2.170015 45.00548 183.2203  8245.919
#> 6 5 [h] 0.9765872 2.170015 45.00548 174.5957  7857.761
```

<sup>Created on 2021-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

This is likely because of the ADVAN equations that RxODE uses;  Perhaps as a new feature if Q is zero it downgrades to the 1 compartment solution, but that isn't something that is currently done.

**Comment by snailittle** [comment]
Hi MattMany thanks for investigating into this issue. I am curious why the Q=0 works for IV bolus but not IV infusion.  How does the dosing parameters get affected by Q?For my case I am trying to use one model to simulate different scenarios using one model, and setting Q=0 is one convenient approach to have one model dealing with both one and two compartment simulations.
Penny
    On Friday, May 21, 2021, 11:42:59 AM EDT, Matthew Fidler ***@***.***> wrote:  
 
 


Yes, I can reproduce:
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  Q =  TQ * exp(eta.Q)
  V3 =  TV3 * exp(eta.V3)
  A2   = linCmt(KA, CL, V2, Q, V3);
  Conc = A2/V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01, # central
    TQ=0,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1,
                                                  0,0.04,0.04,0.1,
                                                  0,0.02,0.02,0.04,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1,
         0,0.04,0.04,0.1,
         0,0.02,0.02,0.04,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~",
                                deparse1(etacov), ")")))



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time        KA       CL       V2 Q      V3  A2 Conc
#> 1 0 [h] 0.8796147 1.809866 42.21216 0 550.746   0    0
#> 2 1 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 3 2 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 4 3 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 5 4 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN
#> 6 5 [h] 0.8796147 1.809866 42.21216 0 550.746 NaN  NaN


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2 Q       V3       A2      Conc
#> 1 0 [h] 0.8262963 1.138734 29.96948 0 328.6137 333.6728 11.133753
#> 2 1 [h] 0.8262963 1.138734 29.96948 0 328.6137 321.2323 10.718646
#> 3 2 [h] 0.8262963 1.138734 29.96948 0 328.6137 309.2555 10.319016
#> 4 3 [h] 0.8262963 1.138734 29.96948 0 328.6137 297.7254  9.934286
#> 5 4 [h] 0.8262963 1.138734 29.96948 0 328.6137 286.6251  9.563899
#> 6 5 [h] 0.8262963 1.138734 29.96948 0 328.6137 275.9387  9.207322
Created on 2021-05-21 by the reprex package (v2.0.0)

Here you are using Q=0, but the equations that RxODE currently uses requires the parameter to be non-zero; Also you have the concentration defined incorrectly. I have updated the code so that it produces the correct values:
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  Q =  TQ * exp(eta.Q)
  V3 =  TV3 * exp(eta.V3)
  Conc = linCmt(KA, CL, V2, Q, V3);
  A2 = Conc * V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01, # central
    TQ=1,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1,
                                                  0,0.04,0.04,0.1,
                                                  0,0.02,0.02,0.04,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1,
         0,0.04,0.04,0.1,
         0,0.02,0.02,0.04,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL+eta.V2+eta.Q+eta.V3~",
                                deparse1(etacov), ")")))



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time       KA       CL       V2         Q       V3      Conc       A2
#> 1 0 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008   0.00000    0.000
#> 2 1 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008  39.87928 1938.183
#> 3 2 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008  77.32001 3757.849
#> 4 3 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 112.47281 5466.320
#> 5 4 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 145.47898 7070.461
#> 6 5 [h] 0.536866 2.146253 48.60126 0.9223214 449.5008 176.47111 8576.718


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2         Q      V3     Conc        A2
#> 1 0 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 206.9936 10000.000
#> 2 1 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 197.1502  9524.457
#> 3 2 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 187.7837  9071.956
#> 4 3 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 178.8710  8641.378
#> 5 4 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 170.3901  8231.661
#> 6 5 [h] 0.9870771 1.673596 48.31067 0.6813083 213.568 162.3201  7841.793
Created on 2021-05-21 by the reprex package (v2.0.0)

If you wish to use a simple 1 compartment model, this will still work but you currently have to drop the Q value.
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

mod2 <- RxODE({

  KA =  TKA * exp(eta.KA)
  CL =  TCL * exp(eta.CL)
  V2 =  TV2 * exp(eta.V2)
  #Q =  TQ * exp(eta.Q)
  #V3 =  TV3 * exp(eta.V3)
  Conc = linCmt(KA, CL, V2);
  A2 = Conc * V2;

})

ev <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000, rate=2000, nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);


theta <-
  c(TKA=0.7, TCL=0.186E+01, TV2=4.02E+01 # central
    #TQ=1,  TV3=2.97E+02             # peripheral
)               # effects



omega<- lotri({eta.KA+eta.CL+eta.V2~c(0.1,
                                                  0,0.1,
                                                  0,0.06,0.1)})




etacov=c(0.1,
         0,0.1,
         0,0.06,0.1)
omega <- eval(parse(text=paste0("lotri(eta.KA+eta.CL~",
                                deparse1(etacov), ")")))
#> Error: number of items and lower triangular matrix mismatch



######## This simulation with IV infusion did NOT work
x <- mod2 %>%  solve(theta, omega=omega, ev, nsub=4)
head(x)
#>    time       KA       CL      V2      Conc       A2
#> 1 0 [h] 0.868973 2.141941 39.6459   0.00000    0.000
#> 2 1 [h] 0.868973 2.141941 39.6459  49.10806 1946.933
#> 3 2 [h] 0.868973 2.141941 39.6459  95.63337 3791.471
#> 4 3 [h] 0.868973 2.141941 39.6459 139.71176 5538.998
#> 5 4 [h] 0.868973 2.141941 39.6459 181.47192 7194.617
#> 6 5 [h] 0.868973 2.141941 39.6459 221.03578 8763.161


######## This simulation with IV bolus did work

ev2 <- eventTable(amount.units='mg', time.units='hours') %>%
  add.dosing(dose=10000,  nbr.doses=10, dosing.interval=12,dosing.to=2) %>%
  add.sampling(0:240);

x <- mod2 %>%  solve(theta, omega=omega, ev2, nsub=4)
head(x)
#>    time        KA       CL       V2     Conc        A2
#> 1 0 [h] 0.9765872 2.170015 45.00548 222.1952 10000.000
#> 2 1 [h] 0.9765872 2.170015 45.00548 211.7358  9529.273
#> 3 2 [h] 0.9765872 2.170015 45.00548 201.7689  9080.704
#> 4 3 [h] 0.9765872 2.170015 45.00548 192.2711  8653.251
#> 5 4 [h] 0.9765872 2.170015 45.00548 183.2203  8245.919
#> 6 5 [h] 0.9765872 2.170015 45.00548 174.5957  7857.761
Created on 2021-05-21 by the reprex package (v2.0.0)

This is likely because of the ADVAN equations that RxODE uses; Perhaps as a new feature if Q is zero it downgrades to the 1 compartment solution, but that isn't something that is currently done.

**Comment by mattfidler** [comment]
I think it is because of the parameter transformation, though I'm unsure.  The `rxDerived()` is a front end to the transformation between the supplied parameters and the output parameters.

In this case we have:

``` r
library(RxODE)
#> RxODE 1.0.9 using 4 threads (see ?getRxThreads)

rxDerived(KA=0.7, CL=0.186E+01, V2=4.02E+01, # central
    Q=0,  V3=2.97E+02             # peripheral
    )
#>     vc        kel k12 k21  vp vss   cl q t12alpha t12beta      alpha beta
#> 1 40.2 0.04626866   0   0 NaN NaN 1.86 0 14.98092     Inf 0.04626866    0
#>            A B fracA fracB
#> 1 0.02487562 0     1     0
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
