### ISSUE TITLE
Simulate as per a NONMEM dataset with AMT, EVID, TIME, and POSTHOC estimate columns [Error in et.default(., evid = nm1.2$EVID) : evid cannot be a vector] 

### ISSUE THREAD

**Issue by nitkaila** [nlmixrdevelopment/RxODE#421]
Hi Matt.  I am attempting to simulate individual profiles, with PK sampling times and dosing information exactly as in the nonmem dataset, using posthoc estimates.  I create a data.frame and a tibble (nm1.2, cov.df.2) below.  However, it is not simply possible to read into event table, et() the 'evid', 'amt' and 'cmt' as vectors directly from the nonmem dataset format.  Is there an easier way or an example, to read in 'evid', 'amt' and 'cmt' columns from a nonmem dataset into 'et' to perform individual level simulations, using the posthoc estimates of the model parameters.

Thanks in advance,

Nitin    

```r
> nm1.2
   ID   TIME EVID CMT AMT
1   1   0.00    1   1  30
2   1   0.30    0   2   0
3   1   0.75    0   2   0
4   1   1.25    0   2   0
5   1   2.00    0   2   0
6   1   3.00    0   2   0
7   1   4.00    0   2   0
8   1   6.00    0   2   0
9   1   8.02    0   2   0
10  1  10.00    0   2   0
11  1  12.07    0   2   0
12  1  24.00    0   2   0
13  1  36.00    0   2   0
14  1  48.00    0   2   0
15  1 456.00    1   1 300
16  1 456.40    0   2   0
17  1 456.75    0   2   0
18  1 457.28    0   2   0
19  1 458.00    0   2   0
20  1 459.05    0   2   0
21  1 460.03    0   2   0
22  1 462.02    0   2   0
23  1 464.03    0   2   0
24  1 466.00    0   2   0
25  1 468.10    0   2   0
26  1 480.00    0   2   0
27  1 492.00    0   2   0
28  1 504.00    0   2   0
29  2   0.00    1   1   3
30  2   0.33    0   2   0
31  2   0.75    0   2   0
32  2   1.25    0   2   0
33  2   2.00    0   2   0
34  2   3.00    0   2   0
35  2   4.00    0   2   0
36  2   6.00    0   2   0
37  2   8.00    0   2   0
38  2  10.00    0   2   0
39  2  12.00    0   2   0
40  2  24.00    0   2   0
41  2  36.00    0   2   0
42  2  48.00    0   2   0
43  2 384.00    1   1  30
44  2 384.30    0   2   0
45  2 384.75    0   2   0
46  2 385.25    0   2   0
47  2 386.00    0   2   0
48  2 387.00    0   2   0
49  2 388.00    0   2   0
50  2 390.00    0   2   0
51  2 392.03    0   2   0
52  2 394.00    0   2   0
53  2 396.00    0   2   0
54  2 408.03    0   2   0
55  2 420.00    0   2   0
56  2 432.00    0   2   0
57  2 840.00    1   1 300
58  2 840.30    0   2   0
59  2 840.75    0   2   0
60  2 841.25    0   2   0
61  2 842.00    0   2   0
62  2 843.00    0   2   0
63  2 844.00    0   2   0
64  2 846.00    0   2   0
65  2 848.02    0   2   0
66  2 850.00    0   2   0
67  2 852.00    0   2   0
68  2 864.00    0   2   0
69  2 876.03    0   2   0
70  2 888.00    0   2   0

> cov.df.2
# A tibble: 2 x 14
     id  BBMI  PTST  TRT1  TRT2   BWT   FED   DKA  DOSE    CL    V1    V2     Q    KA
  <int> <dbl> <int> <dbl> <dbl> <dbl> <int> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1     1  27.7     0     1     0  87.2     0  0.6     30 150.  519.  221.   6.35 0.212
2     2  22.4     0     1     0  62.1     0  0.06     3  63.5  80.7  28.1  1.18 0.173


### evid, amt vector error #### 

> e <- et() %>%
+   #et(id=cov.df$id, amt=15000,cmt="depot",addl=1,ii=12) %>%
+   et(id=cov.df.2$id) %>% #, amt=nm1.2$AMT,cmt="depot") %>%
+   et(time=nm1.2$TIME) %>%
+   
+   et(evid=nm1.2$EVID) %>%
+   #et(amt=nm1.2$AMT) %>%
+   
+   as.data.frame %>%
+   ## Merge the event table with the covarite information
+   merge(cov.df.2,by="id") %>%
+   as_tibble
Error in et.default(., evid = nm1.2$EVID) : evid cannot be a vector
```

**Comment by mattfidler** [comment]
Hi Nittin,

You actually do not need to use `et()` to create an event table.  You can use the NONMEM dataset directly.  This makes simulating individuals matching NONMEM a simple matter of merging the posthoc estimates from NONMEM onto the original dataset. 

Hopefully this is helpful.  It is much easier than trying to get this information in an event table as you are showing.  

If you need help, please use a dummy dataset so I can reproduce the results.

Thank you for your patience in the response.

**Comment by nitkaila** [comment]
> Hi Nittin,
> 
> You actually do not need to use `et()` to create an event table. You can use the NONMEM dataset directly. This makes simulating individuals matching NONMEM a simple matter of merging the posthoc estimates from NONMEM onto the original dataset.
> 
> Hopefully this is helpful. It is much easier than trying to get this information in an event table as you are showing.
> 
> If you need help, please use a dummy dataset so I can reproduce the results.
> 
> Thank you for your patience in the response.

Hi Matt,

Thanks so much.  I did not realize that a NONMEM dataset could directly be read in to perform simulation in RxODE.  

Nitin

> nm1.2
   id ID   TIME EVID CMT   AMT BBMI PTST TRT1 TRT2  BWT FED  DKA DOSE      CL      V1      V2     Q      KA
1   1  1   0.00    1   1 3e+04 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
2   1  1   0.30    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
3   1  1   0.75    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
4   1  1   1.25    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
5   1  1   2.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
6   1  1   3.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
7   1  1   4.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
8   1  1   6.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
9   1  1   8.02    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
10  1  1  10.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
11  1  1  12.07    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
12  1  1  24.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
13  1  1  36.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
14  1  1  48.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
15  1  1 456.00    1   1 3e+05 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
16  1  1 456.40    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
17  1  1 456.75    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
18  1  1 457.28    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
19  1  1 458.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
20  1  1 459.05    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
21  1  1 460.03    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
22  1  1 462.02    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
23  1  1 464.03    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
24  1  1 466.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
25  1  1 468.10    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
26  1  1 480.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
27  1  1 492.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
28  1  1 504.00    0   2 0e+00 27.7    0    1    0 87.2   0 0.60   30 149.960 518.890 220.870 6.347 0.21241
29  2  2   0.00    1   1 3e+03 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
30  2  2   0.33    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
31  2  2   0.75    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
32  2  2   1.25    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
33  2  2   2.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
34  2  2   3.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
35  2  2   4.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
36  2  2   6.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
37  2  2   8.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
38  2  2  10.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
39  2  2  12.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
40  2  2  24.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
41  2  2  36.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
42  2  2  48.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
43  2  2 384.00    1   1 3e+04 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
44  2  2 384.30    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
45  2  2 384.75    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
46  2  2 385.25    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
47  2  2 386.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
48  2  2 387.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
49  2  2 388.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
50  2  2 390.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
51  2  2 392.03    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251
52  2  2 394.00    0   2 0e+00 22.4    0    1    0 62.1   0 0.06    3  63.532  80.705  28.126 1.184 0.17251

> sim1 <-  rxSolve(mod1, nm1.2, nSub=2, nStud=1,
+           theta,       
+           addDosing=T,addCov=T,simVariability=F) 

> dall<-as.data.frame(sim1[,c("id","evid","cmt","amt","time","C2")])

> dall
   id evid cmt   amt       time           C2
1   1    1   1 3e+04   0.240471 0.000000e+00
2   1    0  NA    NA   0.300000 2.053984e+00
3   1    0  NA    NA   0.750000 1.516685e+01
4   1    0  NA    NA   1.250000 2.555832e+01
5   1    0  NA    NA   2.000000 3.509288e+01
6   1    0  NA    NA   3.000000 4.036495e+01
7   1    0  NA    NA   4.000000 4.069395e+01
8   1    0  NA    NA   6.000000 3.502311e+01
9   1    0  NA    NA   8.020000 2.728310e+01
10  1    0  NA    NA  10.000000 2.051739e+01
11  1    0  NA    NA  12.070000 1.494200e+01
12  1    0  NA    NA  24.000000 2.288813e+00
13  1    0  NA    NA  36.000000 4.283604e-01
14  1    0  NA    NA  48.000000 1.363738e-01
15  1    1   1 3e+05 456.240471 2.711954e-07
16  1    0  NA    NA 456.400000 5.325787e+01
17  1    0  NA    NA 456.750000 1.516685e+02
18  1    0  NA    NA 457.280000 2.606533e+02
19  1    0  NA    NA 458.000000 3.509288e+02
20  1    0  NA    NA 459.050000 4.047371e+02
21  1    0  NA    NA 460.030000 4.065530e+02
22  1    0  NA    NA 462.020000 3.494842e+02
23  1    0  NA    NA 464.030000 2.724586e+02
24  1    0  NA    NA 466.000000 2.051740e+02
25  1    0  NA    NA 468.100000 1.487229e+02
26  1    0  NA    NA 480.000000 2.288815e+01
27  1    0  NA    NA 492.000000 4.283602e+00
28  1    0  NA    NA 504.000000 1.363736e+00
29  2    1   1 3e+03   0.240471 0.000000e+00
30  2    0  NA    NA   0.330000 2.042422e-01
31  2    0  NA    NA   0.750000 1.033616e+00
32  2    0  NA    NA   1.250000 1.782624e+00
33  2    0  NA    NA   2.000000 2.528649e+00
34  2    0  NA    NA   3.000000 3.025394e+00
35  2    0  NA    NA   4.000000 3.158514e+00
36  2    0  NA    NA   6.000000 2.879160e+00
37  2    0  NA    NA   8.000000 2.347495e+00
38  2    0  NA    NA  10.000000 1.815707e+00
39  2    0  NA    NA  12.000000 1.365704e+00
40  2    0  NA    NA  24.000000 2.122588e-01
41  2    0  NA    NA  36.000000 3.741960e-02
42  2    0  NA    NA  48.000000 1.067456e-02
43  2    1   1 3e+04 384.240471 1.773216e-07
44  2    0  NA    NA 384.300000 1.369513e+00
45  2    0  NA    NA 384.750000 1.033616e+01
46  2    0  NA    NA 385.250000 1.782624e+01
47  2    0  NA    NA 386.000000 2.528649e+01
48  2    0  NA    NA 387.000000 3.025393e+01
49  2    0  NA    NA 388.000000 3.158514e+01
50  2    0  NA    NA 390.000000 2.879159e+01
51  2    0  NA    NA 392.030000 2.339176e+01
52  2    0  NA    NA 394.000000 1.815707e+01
53  2    0  NA    NA 396.000000 1.365704e+01
54  2    0  NA    NA 408.030000 2.112743e+00
55  2    0  NA    NA 420.000000 3.741948e-01
56  2    0  NA    NA 432.000000 1.067454e-01
57  2    1   1 3e+05 840.240471 1.844434e-07
58  2    0  NA    NA 840.300000 1.369513e+01
59  2    0  NA    NA 840.750000 1.033616e+02
60  2    0  NA    NA 841.250000 1.782624e+02
61  2    0  NA    NA 842.000000 2.528649e+02
62  2    0  NA    NA 843.000000 3.025393e+02
63  2    0  NA    NA 844.000000 3.158514e+02
64  2    0  NA    NA 846.000000 2.879159e+02
65  2    0  NA    NA 848.020000 2.341949e+02
66  2    0  NA    NA 850.000000 1.815707e+02
67  2    0  NA    NA 852.000000 1.365704e+02
68  2    0  NA    NA 864.000000 2.122587e+01
69  2    0  NA    NA 876.030000 3.727488e+00
70  2    0  NA    NA 888.000000 1.067454e+00
