### ISSUE TITLE
Compilation error due to file not found.

### ISSUE THREAD

**Issue by kevin199011** [nlmixrdevelopment/RxODE#440]
Hi, I just installed RxODE and was testing it. Library installation was fine, however, when I run below test script, there was problem compiling. See below error:

> rx_3feabb99947fcdaf31b146fc7977be6c_x64.c:72:10: fatal error: RxODE_model_shared.h: No such file or directory
>  #include <RxODE_model_shared.h>
>           ^~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.

I checked the library folder and the RxODE_model_shared.h file is there. Any idea why this happened? Thank you!

Best

```r
library(RxODE)
set.seed(1)

mod1 <-RxODE({
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
})
```

Below please see the sessionInfo:

>R version 4.0.5 (2021-03-31)
>Platform: x86_64-w64-mingw32/x64 (64-bit)
>Running under: Windows 10 x64 (build 19042)

>Matrix products: default

>locale:
>[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
>[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    
>system code page: 936

>attached base packages:
>[1] stats     graphics  grDevices utils     datasets  methods   base     

> other attached packages:
> [1] RxODE_1.0.9
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_1.0.6          pillar_1.6.1        compiler_4.0.5      PreciseSums_0.4     tools_4.0.5         sys_3.4            
>  [7] qs_0.24.1           digest_0.6.27       memoise_2.0.0       lifecycle_1.0.0     tibble_3.1.2        gtable_0.3.0       
> [13] checkmate_2.0.0     pkgconfig_2.0.3     rlang_0.4.11        rstudioapi_0.13     DBI_1.1.1           cli_2.5.0          
> [19] xfun_0.23           fastmap_1.1.0       knitr_1.33          dplyr_1.0.6         generics_0.1.0      vctrs_0.3.8        
> [25] grid_4.0.5          tidyselect_1.1.1    glue_1.4.2          data.table_1.14.0   RApiSerialize_0.1.0 R6_2.5.0           
> [31] fansi_0.4.2         dparser_1.3.1-4     ggplot2_3.3.3       purrr_0.3.4         magrittr_2.0.1      backports_1.2.1    
> [37] scales_1.1.1        ellipsis_0.3.2      assertthat_0.2.1    colorspace_2.0-1    utf8_1.2.1          stringfish_0.15.1  
> [43] lotri_0.3.1         RcppParallel_5.1.4  munsell_0.5.0       cachem_1.0.5        crayon_1.4.1

**Comment by mattfidler** [comment]
I personally see errors like this when: 

- the R installation is in a network or cloud location
- the temporary directory is in a network or cloud location
- the home directory is in a network or cloud location

It is also possible that the location of any these items contain either spaces or international characters.  Other than that I am unsure what it could be...

Are any of these true for your setup?  If you need help figuring out if this is true, let me know

**Comment by kevin199011** [comment]
Hi Matt, the R installation and the home directory (Documents folder) are in network, instead of being the C:/Documents folder. Is there any solution to this issue? Thank you!

**Comment by mattfidler** [comment]
Based on organizations and your name you may have either a network drive attached to your home directory or have international characters in your name. Either can be problematic for R and for certain R packages nlmixr interacts with. To be safe a $HOME directory should be changed to a user-writable location without any international characters, for example c:/tmp
In windows this can be done by going to the control panel and searching for “environment variables. The search should bring up “Edit environmental variables for your account”

![image](https://user-images.githubusercontent.com/514778/125346330-39507e80-e31f-11eb-8d5b-e939296d1e4a.png)Here 

You should be able to add a new environmental variable called “HOME” that will point to an appropriate writable directory. This will allow many R packages and other windows libraries to work correctly.

**Comment by mattfidler** [comment]
I am hoping this worked for you.  If not, feel free to open another issue
