### ISSUE TITLE
shinyapps.io

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#45]
When using `shinyapps.io` from windows and using `genShinyApp.template` get the following errors:

```
Warning: Error in rxSolve.default: Cannot load RxODE dlls for this model.
```

This is because the `dll` files are compiled for windows and then uploaded on a linux box (or at least a non-windows machine).  

A work around is changing the loading of `rx_shiny_data` in the `server.R`:

```R
load(file.path("./rx_shiny_data.rda"))
if (!rxDynLoad(mod1)) mod1 <- RxODE(mod1, modName="mod1")
```

Note that shinyapps.io also requires non-absolute directories.  Therefore, the `wd` shouldn't be modified.

**Comment by mattfidler** [comment]
Not now.

**Comment by ncpunt** [comment]
Is there a way of downloading the generated DLL (e.g. mod_x64.dll) from the shinyapps.io server?
