### ISSUE TITLE
initial condition outside RxODE function

### ISSUE THREAD

**Issue by namtien0312** [nlmixrdevelopment/RxODE#458]
Dear RxODE team,

I try to create the initial condition for the ODE solver outside the RxODE function, but it doesn't work. I don't know why the first row of `output` doesn't have 'drug amount'.

Thank you for answer my question.

```
library(RxODE)

mod1 = RxODE({
    tvCL = 5.27
    tvVc = 17.2
    tvQ = 9.92
    tvVp = 10.6
    #eta.IIV.Cl ~ log(0.265^2 + 1)
    #eta.IIV.Vc ~ log(0.307^2 + 1)
    Cl = tvCL*(1 + 0.014*(Clcr - 39.0)*(60/1000))*(1 + 0.007*(Wt - 75))#*exp(eta.IIV.Cl)
    Vc = tvVc*(1 + 0.0225*(Wt - 75))#*exp(eta.IIV.Vc)
    Q = tvQ
    Vp = tvVp
    d/dt(Central) = -Central*(Cl/Vc + Q/Vc) + Peri*Q/Vp
    d/dt(Peri) =  Central*Q/Vc - Peri*Q/Vp
    Cp = Central/Vc
})

inits = c(Central = 500, Peri = 200)

df_abs1 = mod1  %>%  
    et(amt = 1000, cmt = 1, dur = 3) %>%
    et(seq(0, 3, by = 0.1)) %>% 
    et(id = 1)  %>% 
    rxSolve(
        inits,
        iCov = data.frame(id = 1, Wt = 75, Clcr = 50),
        keep = c("Wt", "Clcr")
    )  %>% 
    data.frame()
```

![image](https://user-images.githubusercontent.com/68368676/131221570-a4eae7d2-4987-49a9-837d-8a6a94ccb8c4.png)

**Comment by namtien0312** [comment]
> Dear RxODE team,
> 
> I try to create the initial condition for the ODE solver outside the RxODE function, but it doesn't work. I don't know why the first row of `output` doesn't have 'drug amount'.
> 
> Thank you for answer my question.
> 
> ```
> library(RxODE)
> 
> mod1 = RxODE({
>     tvCL = 5.27
>     tvVc = 17.2
>     tvQ = 9.92
>     tvVp = 10.6
>     #eta.IIV.Cl ~ log(0.265^2 + 1)
>     #eta.IIV.Vc ~ log(0.307^2 + 1)
>     Cl = tvCL*(1 + 0.014*(Clcr - 39.0)*(60/1000))*(1 + 0.007*(Wt - 75))#*exp(eta.IIV.Cl)
>     Vc = tvVc*(1 + 0.0225*(Wt - 75))#*exp(eta.IIV.Vc)
>     Q = tvQ
>     Vp = tvVp
>     d/dt(Central) = -Central*(Cl/Vc + Q/Vc) + Peri*Q/Vp
>     d/dt(Peri) =  Central*Q/Vc - Peri*Q/Vp
>     Cp = Central/Vc
> })
> 
> inits = c(Central = 500, Peri = 200)
> 
> df_abs1 = mod1  %>%  
>     et(amt = 1000, cmt = 1, dur = 3) %>%
>     et(seq(0, 3, by = 0.1)) %>% 
>     et(id = 1)  %>% 
>     rxSolve(
>         inits,
>         iCov = data.frame(id = 1, Wt = 75, Clcr = 50),
>         keep = c("Wt", "Clcr")
>     )  %>% 
>     data.frame()
> ```
> 
> ![image](https://user-images.githubusercontent.com/68368676/131221570-a4eae7d2-4987-49a9-837d-8a6a94ccb8c4.png)

**Comment by namtien0312** [comment]
Sorry, I just change the `inits = inits` in the `rxSolve` function and it works.

**Comment by mattfidler** [comment]
Great. I am glad to hear it
