### ISSUE TITLE
Can define thetaLower = 0 for several parameters and = -Inf for rest?

### ISSUE THREAD

**Issue by namtien0312** [nlmixrdevelopment/RxODE#462]
Dear `nlmixr/RxODE` team,

I'm trying to simulate with parameter uncertainty using the [rxSolve](https://nlmixrdevelopment.github.io/RxODE/reference/rxSolve.html) function but I want to fix the lower boundary of several parameters such as Vd, Cl to 0 using `thetaLower` = 0, but other parameters don't restrict by lower boundary, i.e with <br> `thetaLower` = `-Inf`.

Can I have a way to solve this? Thank you very much for answering!

And additionally, Can you explain the meaning of `dfSub` and `dfObs` arguments and how to set these? [And for example](https://www.pmxsolutions.com/2019/01/31/how-to-simulate-your-pharmacometric-model-with-parameter-uncertainty/), in `mgrsolve` package, I don't need to define these arguments.

**Comment by mattfidler** [comment]
Hi @namtien0312,  

The following website shows the simulation with uncertainty options

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-sim-var.html

In short you should be able to have `thetaLower` be a named vector `thetaLower=c(Vd=0,Cl=0)`

`dfSub` specifies the degrees of freedom for the covariance simulations on the `omega`  component (often the number of subjects though Uppusula University defines it a bit differently) and `dfObs` (the number of observations for the residual covariance matrix).

These by default simulate from the conjute prior of the covariance matrix, the inverse wishart.  You do not have to supply them in `RxODE` just like you don't have to define this in `mrgsolve`.  However, It highly suggest using the uncertainty in the `omega` matrix.

Note that there is a package to simulate the uncertainty in `omega` matrix and `sigma` matrix in `mrgsolve` by @kylebaron.  However, I cannot recall what it is (perhaps he would be so kind to let you know).  So even though the example you cited didn't use it, you can simulate in the same manner in `mrgsolve`.

As to why things are different between `mrgsolve` and `RxODE`, they are different packages.

**Comment by namtien0312** [comment]
Thank you very much for your help and explanation, sorry for the late response!

Is it if I have a 'built model' with a dataset of 20 patients and 3 samples per patient, then should I set `dfSub` = 20 and `dfObs` = 60 for simulation with parameter uncertainty? And if I had a published popPK model build with 30 patients, 100 samples then should I define `dfSub` = 30 and `dfObs` = 100 for simulating with parameter uncertainty?

Thank you!

**Comment by mattfidler** [comment]
Yes.  That will simulate with the prior information you have.

The nStud is the number of times you simulate from your prior distribution

**Comment by namtien0312** [comment]
Thank you Dr. Fidler for your help.

**Comment by mattfidler** [comment]
No problem

**Comment by mattfidler** [comment]
Hi @namtien0312,

Thank you for your patience.  I would say that some of the ODEs are solved incorrectly because it is difficult to solve.  One way to approach this is to reduce the `atol` and `rtol`.  Another way is to simulate more than needed and then take the first X subjects without the `NA` values.
