### ISSUE TITLE
An floating point issue?

### ISSUE THREAD

**Issue by lirui0321** [nlmixrdevelopment/RxODE#478]
Hi Matt,

When I try to solve something like 0^1 with RxODE, I end up with a tiny number like 1.490116e-08, instead of zero. It feels like a floating point issue from my weak recollection of my numerical analysis class taken 15 years ago, but I am not sure. 

Do I get a correct understanding of the problem? What would be your recommendation in dealing with something like this? Thank you very much!

Rui 

`mod = RxODE({A = 0^1})`
`ev = et() %>% add.sampling(seq(0,30, by = 0.1))`
`x <- mod$solve( ev)`

**Comment by mattfidler** [comment]
Yes, this is part of it.  Additionally `RxODE` and `rxode2` have divide by zero protection and other sorts of options to make ODE solving in estimation a bit more stable.   

In this case it is a floating point issue, I believe.  

If you want to make sure, you could turn off the safe zero options,  as in the following example:

``` r
library(rxode2)
#> Warning: package 'rxode2' was built under R version 4.2.1
#> rxode2 2.0.7 using 4 threads (see ?getRxThreads)
#>   no cache: create with `rxCreateCache()`

mod = RxODE({A = 0^1})
ev = et() %>% add.sampling(seq(0,30, by = 0.1))
x <- rxSolve(mod, ev,safeZero = FALSE)


x
#> ── Solved rxode2 object ──
#> ── Parameters (x$params): ──
#> # A tibble: 1 × 0
#> ── Initial Conditions (x$inits): ──
#> named numeric(0)
#> ── First part of data (object): ──
#> # A tibble: 301 × 2
#>    time            A
#>   <dbl>        <dbl>
#> 1   0   0.0000000149
#> 2   0.1 0.0000000149
#> 3   0.2 0.0000000149
#> 4   0.3 0.0000000149
#> 5   0.4 0.0000000149
#> 6   0.5 0.0000000149
#> # … with 295 more rows

x2 <- rxSolve(mod, ev,safeZero = TRUE)

x2 
#> ── Solved rxode2 object ──
#> ── Parameters (x$params): ──
#> # A tibble: 1 × 0
#> ── Initial Conditions (x$inits): ──
#> named numeric(0)
#> ── First part of data (object): ──
#> # A tibble: 301 × 2
#>    time            A
#>   <dbl>        <dbl>
#> 1   0   0.0000000149
#> 2   0.1 0.0000000149
#> 3   0.2 0.0000000149
#> 4   0.3 0.0000000149
#> 5   0.4 0.0000000149
#> 6   0.5 0.0000000149
#> # … with 295 more rows
```

<sup>Created on 2022-08-30 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by lirui0321** [comment]
Thanks, Matt! That helps!
