### ISSUE TITLE
An issue with the OMEGA

### ISSUE THREAD

**Issue by Slow-Walker66** [nlmixrdevelopment/RxODE#482]
Hello, 
I met a problem when I reproduced others model, the error was "Error in rxSolveSEXP(object, .ctl, .nms, .xtra, params, events, inits,  : 
  'omega' must be symmetric". The codes were below, thanks in advance:

set.seed(1234)
rxSetSeed(1234)

mod6 <- RxODE({
  CL   = TVCL*exp(eta.CL);
  V    = TVV*exp(eta.V);
  KA   = TVKA*exp(eta.KA); 
  
  conc = centr/V;
  d/dt(depot) =  -KA * depot;
  d/dt(centr) =  KA * depot - CL * conc;
  
  cp = conc * (1+prop.err)
})

# Define typical patient: EM/RM
BW <- 70   # kg
AGE <- 30  # population meidan age setting as 30 years[45]
BMI <- 27  # population median BMI setting 27

# Define fixed effect parameters--EM/RM
theta <- c(TVCL = 26*(AGE/40)^(-0.336)*(BW/76)^(0.333), 
           TVV  = 947*(BMI/27)^(1.11), 
           TVKA = 0.8)

# Define between subject variability
omega <- lotri({eta.CL + eta.V + eta.KA ~ c(0.235225,
                                                                      0.008836,0.3844,
                                                                      0.228484,0.660969,0.622521)})

# Define unexplained variability
sigma <- lotri(prop.err ~ 0.289^2)

# DOSE of SCIT input qd ------------------------------------------------
dose_scit6 <- 10 # 10 mg/d [5-20mg/d actually]

# Define event record
ev6 <- et(amount.units = "mg", time.units = "hours") %>%
  add.dosing(dosing.to = "depot",
             dose = dose_scit6,  # mg
             nbr.doses = 10, 
             dosing.interval = 24,
             start.time = 0) %>%
  # 0-24h after the last dose
  add.sampling(seq(from=216,to=240,by=1))

# Perform simulation
# total number of subject: 1000
sim11  <- rxSolve(mod6,theta,ev6,omega=omega,sigma=sigma,nSub=1000)

**Comment by mattfidler** [comment]
Hi @Slow-Walker66 

I no longer develop `RxODE` and have switched to developing `rxode2` (see https://blog.nlmixr2.org/blog/2022-10-12-rxode-and-rxode2/).

However the following `rxode2` code should work with both packages.  In general, ti converted the `omega` matrix to the nearest positive definite matrix.

```r
library(rxode2)

set.seed(1234)
rxSetSeed(1234)

mod6 <- RxODE({
CL = TVCL*exp(eta.CL);
V = TVV*exp(eta.V);
KA = TVKA*exp(eta.KA);

conc = centr/V;
d/dt(depot) = -KA * depot;
d/dt(centr) = KA * depot - CL * conc;

cp = conc * (1+prop.err)
})

# Define typical patient: EM/RM
BW <- 70 # kg
AGE <- 30 # population meidan age setting as 30 years[45]
BMI <- 27 # population median BMI setting 27

#Define fixed effect parameters--EM/RM
theta <- c(TVCL = 26*(AGE/40)^(-0.336)*(BW/76)^(0.333),
           TVV = 947*(BMI/27)^(1.11),
           TVKA = 0.8)

#Define between subject variability
omega <- lotri({eta.CL + eta.V + eta.KA ~ c(0.235225,
0.008836,0.3844,
0.228484,0.660969,0.622521)})

# Make the mega matrix positive definite and pre-calculate cholesky decomp
omega <- chol(as.matrix((Matrix::nearPD(omega)$mat)))


# Define unexplained variability
sigma <- lotri(prop.err ~ 0.289^2)

# DOSE of SCIT input qd ------------------------------------------------
dose_scit6 <- 10 # 10 mg/d [5-20mg/d actually]

#Define event record
ev6 <- et(amount.units = "mg", time.units = "hours") %>%
  add.dosing(dosing.to = "depot",
             dose = dose_scit6, # mg
             nbr.doses = 10,
             dosing.interval = 24,
             start.time = 0) %>%
  #0-24h after the last dose
  add.sampling(seq(from=216,to=240,by=1))

#Perform simulation
#total number of subject: 1000
sim11 <- rxSolve(mod6,theta,ev6,omega=omega,sigma=sigma,nSub=1000, omegaIsChol = TRUE)

```

Hopefully this works for you!
