### ISSUE TITLE
how to specify the off-diagonal elements of a OMEGA block in a trial simulation with the "separation strategy"

### ISSUE THREAD

**Issue by wchg1980** [nlmixrdevelopment/RxODE#486]
Dear Matt,

I have a question concerning the off-diagonal elements of OMEGA block in a trial simulation using RxODE.

According to the RxODE manual, two strategies can be applied for trial simulations: "inverse Wishart" based & covariance matrix based (also called as "separation strategy"). 

With the "separation strategy", omegas need to be specified together with fixed effect parameters in a vector for the "theta=" argument of the rxSolve(), and the full covariance matrix is used for the "thetaMat=" argument for generating uncertainty. 

`theta <- c(tcl=2.63E+01, tv=1.35E+00, tka=4.20E+00, tlag=2.08E-01,
           prop.sd=2.05E-01, add.sd=1.06E-02, crcl.cl=7.17E-03,
           ## Note that since we are using the separation strategy the ETA variances are here too
           eta.cl=7.30E-02,  eta.v=3.80E-02, eta.ka=1.91E+00)`

`thetaMat <- lotri(
    tcl + tv + tka + tlag + prop.sd + add.sd + crcl.cl + eta.cl + eta.v + eta.ka ~
        c(7.95E-01,
          2.05E-02, 1.92E-03,
          7.22E-02, -8.30E-03, 6.55E-01,
          -3.45E-03, -6.42E-05, 3.22E-03, 2.47E-04,
          8.71E-04, 2.53E-04, -4.71E-03, -5.79E-05, 5.04E-04,
          6.30E-04, -3.17E-06, -6.52E-04, -1.53E-05, -3.14E-05, 1.34E-05,
          -3.30E-04, 5.46E-06, -3.15E-04, 2.46E-06, 3.15E-06, -1.58E-06, 2.88E-06,
          -1.29E-03, -7.97E-05, 1.68E-03, -2.75E-05, -8.26E-05, 1.13E-05, -1.66E-06, 1.58E-04,
          -1.23E-03, -1.27E-05, -1.33E-03, -1.47E-05, -1.03E-04, 1.02E-05, 1.67E-06, 6.68E-05, 1.56E-04,
          7.69E-02, -7.23E-03, 3.74E-01, 1.79E-03, -2.85E-03, 1.18E-05, -2.54E-04, 1.61E-03, -9.03E-04, 3.12E-01))`

How should one specify the off-diagonal elements of the omega matrix in the vector for "theta=" with this strategy? Many thanks!

regards,
Chenguang

**Comment by mattfidler** [comment]
Hi Chenguang,

This can be done by having a full covariance matrix that includes the omega piece within it.  

Here is an example that works with the latest development version of `rxode2`:

https://github.com/nlmixr2/rxode2random/issues/2

It also discusses some of the pros and cons of the approach.

**Comment by wchg1980** [comment]
Thanks for your quick reply! I had a read of the referred discussion but did not find the answer to my question. Perhaps, I can explain it a bit more. The current 2 strategies for trial simulation with IIV are: 

1. use multi-normal to simulate theta & use Inverse-Wishart to simulate OMEGA block
2. ("separation strategy") put the variance of OMEGA matrix (diagonal elements) to _**theta=**_ argument and provide the full var-cov matrix to **_thetaMat=_** , which uses the whole variance-covariance matrix including the correlations between thetas and omegas

For the strategy 1, my perception is that the correlations between fixed effects and random effects are **not** incorporated. So I was wondering if it is possible to use the strategy 2 for the model with full OMEGA block so that correlations between all the parameters could be considered. I did not find such an example and don't know how to specify the off-diagonal random effect e.g. OMEGA(1,2) from NONMEM output in the **_thetaMat_**.  

All my understanding is based on the RxODE user manual on 2021/03/09, but I don't know if there is a change in the nlmixr2/rxode2 .

Thanks again!

**Comment by mattfidler** [comment]
> For the strategy 1, my perception is that the correlations between fixed effects and random effects are not incorporated. So I was wondering if it is possible to use the strategy 2 for the model with full OMEGA block so that correlations between all the parameters could be considered. I did not find such an example and don't know how to specify the off-diagonal random effect e.g. OMEGA(1,2) from NONMEM output in the thetaMat.

This cannot be used in either strategy.  The separation strategy simulates only the diagonals of the omega matrix.

You could simulate all parameters externally in a truncated normal distribution but you would have to manually resimulate if the `omega` is not positive definite.  

There is no method for this simulation.  You would have to make your own.

**Comment by wchg1980** [comment]
Thanks for the clarification!

**Comment by mattfidler** [comment]
No problem,  I think that the inverse Wishart performs the best with correlations, but I understand the desire to account for the fixed and random effect correlation too.

Good luck.
