### ISSUE TITLE
'solve' still returns result even if error solving

### ISSUE THREAD

**Issue by coolbutuseless** [nlmixrdevelopment/RxODE#5]
RxODE v0.61 (github)

I've set up a model which deliberately has a "bad" parameter and won't converge.
I may be interpreting the output incorrectly, but when I run the following code I see 2 errors and a warning (full text of output included at end of issue)

1. Error solving using LSODA
2. Error solving using dop853
3. Originally tried LSODA, but it failed to solve, so used DOP853 instead.

A results matrix is returned, but it is all zeros.

Because the ordering of warnings/messages is not necessarily guaranteed, I'm not sure what to believe 

* did dop853 fail at first and then converge later?
* did both methods fail totally and then just return the equivalent of a 'blank' output with all zeros?

Expected behaviour (if this is actually a case when no solutions found):

* If all solvers fail to converge, an error is thrown and no result is returned.

```{r}

rm(list=ls())
suppressPackageStartupMessages({
  library(RxODE)
})

model_text <- "
  C2 = centr/V2;
  C3 = peri/V3;
  d/dt(depot) =-KA*depot;
  d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
  d/dt(peri)  =                    Q*C2 - Q*C3;
  d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
  "


params <- data.frame(
  KA=2.94E-01, CL=1.86E+01, V2=4.02E+01, # central
  Q=1.05E+01,  V3=2.97E+02,              # peripheral
  Kin=1, Kout=1, EC50=200                # effects
)


event_table <- RxODE::eventTable()
event_table$add.dosing(dose=10000, nbr.doses=10, dosing.interval=12)
event_table$add.sampling(0:240)

#-----------------------------------------------------------------
# Set parameter to something non-sensical
#-----------------------------------------------------------------
params$KA <- -10

model <- RxODE::RxODE(model = model_text)
res   <- model$solve(params=params, events = event_table)

head(res)
```

The (edited) output is included below:

```
> res   <- model$solve(params=params, events = event_table)
DLSODA-  Warning..Internal T (=R1) and H (=R2) are
      such that in the machine, T + H = T on the next step  �
     (H = step size). Solver will continue anyway.
In above message, R1 = 0.0598717, R2 = 2.08841e-18
 
[snipped]
 
DLSODA-  Above warning has been issued I1 times.  
     It will not be issued again for this problem.
In above message, I1 = 10
 
DLSODA-  At current T (=R1), MXSTEP (=I1) steps   
      taken on this call before reaching TOUT     
In above message, I1 = 5000
 
In above message, R1 = 0.0598717
 
IDID=-1, excess work done on this call (perhaps wrong jt).
Error solving using LSODA
Error in try({ : could not solve ODE, IDID = -1 (see further messages)
IDID=-3, step size becomes too small
Error sovling using dop853Error in try({ : Could not solve ODE, IDID = -3 (see further messages).
Warning message:
In model$solve(params = params, events = event_table) :
  Originally tried LSODA, but it failed to solve, so used DOP853 instead.
> 
> head(res)
     time depot centr peri eff C2 C3
[1,]    0 10000     0    0   0  0  0
[2,]    1     0     0    0   0  0  0
[3,]    2     0     0    0   0  0  0
[4,]    3     0     0    0   0  0  0
[5,]    4     0     0    0   0  0  0
[6,]    5     0     0    0   0  0  0
```

**Comment by mattfidler** [comment]
It should have thrown an error.  This is fixed.

**Comment by mattfidler** [comment]
If it doesn't work for you, let me know.

**Comment by coolbutuseless** [comment]
Just tried, and it now correctly throws an error. Thanks for the quick fix!

**Comment by mattfidler** [comment]
Great!  I'm happy it worked for you

**Comment by mattfidler** [comment]
@coolbutuseless I am changing the behavior to just try one solver.  I am also going to allow multilpe IDs to be solved simultaneously.  In this case, only a warning will be issued, and the offending ID(s) will have `NA` values in their compartments.

Keeping you informed since you brought this issue to my attention.
