### ISSUE TITLE
Input file deleted when running RxODE

### ISSUE THREAD

**Issue by lindauer1980** [nlmixrdevelopment/RxODE#50]
Hello,
I have just upgraded today from version 6.1 to version 7.2-5 and found a problem.
When I run RxODE() by pointing to an external txt file that contains the ode, that txt file is actually DELETED during the compilation process, i.e. compilation runs, .dll, .o and .c files are generated but my input file is removed. This did not happen before. Is this a bug or do I need to set some argument in the function call to avoid this behavior?

It happens with the very simple example code:
```
 C2 = centr/V2;
C3 = peri/V3;
d/dt(depot) =-KA*depot;
d/dt(centr) = KA*depot - CL*C2 - Q*C2 + Q*C3;
d/dt(peri)  =                    Q*C2 - Q*C3;
d/dt(eff)  = Kin - Kout*(1-C2/(EC50+C2))*eff;
```

The text above I c&p into the file 'rxodedemo_ode.txt', which disappears when the following line is run)
```R
m1 <- RxODE(filename = 'rxodedemo_ode.txt',modName = 'm1')
```
Note: I also updated today my R installation from 3.3.3 to 3.5.1. 
```R 
SessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RxODE_0.7.2-5

loaded via a namespace (and not attached):
 [1] compiler_3.5.1  lazyeval_0.2.1  magrittr_1.5    rex_1.1.2       tools_3.5.1     mvnfast_0.2.5   yaml_2.2.0     
 [8] memoise_1.1.0   Rcpp_0.12.18    dparser_0.1.8   digest_0.6.16   PreciseSums_0.3
```

Thanks in advance for any help. Regards, Andreas.

**Comment by mattfidler** [comment]
This is definately a bug.

**Comment by wwang-at-github** [comment]
typo or messed-up c&p? i think the syntax should be:
C2 = centr/V2;
C3 = peri/V3;
d/dt(depot) =-KA*
*depot;d/dt(centr) = KA**depot - CL**C2 - Q**C2 + Q*
*C3;d/dt(peri) = Q**C2 - Q*
*C3;d/dt(eff) = Kin - Kout**(1-C2/(EC50+C2))*eff;

**Comment by mattfidler** [comment]
The posted syntax was correct but `*` is the markdown code for *italic* so it didn't display correctly.  I edited the comment and wrapped the code in three backticks.  That way we can see the code.

**Comment by mattfidler** [comment]
Hi @lindauer1980;  Thank you for point this out.  It has been fixed in the latest github release.  You can use it by:

```R
devtools::install_github("nlmixrdevelopment/RxODE")
```

We hope to submit the new version to CRAN soon.

**Comment by mattfidler** [comment]
Please reopen the issue if you still have problems after updating RxODE

**Comment by lindauer1980** [comment]
Thank you very much Matt for the quick help. Works fine now.
