### ISSUE TITLE
Add more support for more types of conditional statements

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#54]
Perhaps add support for:
- `ifelse`
- `else if`
- logical statements in expressions, like in R `H0 = (t < 1.5)*(A+B)`

These are easy enough in RxODE, with the exception of sensitivity parsing....

**Comment by mattfidler** [comment]
Can Also add `max` and `min` since they are a special `ifelse` clause. See Issue #57

**Comment by paolacarrillob** [comment]
Dear Matt, I am struggling with conditional statements for a parameter (gamma). Basically I would  like to have something like:
ifelse(t>=Ton, gamma<-exp(lgamma +eta.gamma),gamma<-0),
where Ton is another parameter that should also be identified. everything I have tried so far returns an evaluation error ('Error in RxODE::etTrans(data, paste(paste(.tmp, collapse = "\n"), "\n",  : 
  Evaluation error: Syntax Errors (see above).)

A work-around this would be great!

**Comment by mattfidler** [comment]
Hi @paolacarrillob ,

`ifelse`, `max`,  `min`, and `else if` are not currently supported.  You can get the correct behavior by:
```R
gma <- 0
if (t >= Ton){
 gma <- exp(tGamma + eta.gamma)
}
```
Note I changed your parameter `lgamma` to `tGamma`. I believe the `lgamma` function is supported in RxODE and may be causing problems.  Unlike base R, function and variables named the same thing likely cause problems.

**Comment by mattfidler** [comment]
I was unaware that R supported assigments in `ifelse`;  Apparently the do

``` r
t = 3
Ton = 4
ifelse(t>=Ton, gamma<-exp(lgamma +eta.gamma),gamma<-0)
#> [1] 0
print(gamma)
#> [1] 0
```

<sup>Created on 2019-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Note another solution is to use the if/else;  This parses well:

``` r

library(RxODE)

tmp <-RxODE({
if (t >= Ton){
 gma <- exp(tGamma + eta.gamma)
} else {
 gma <- 0 
}})

summary(tmp)
#> RxODE 0.9.0-3 model named rx_00518f252742ae4507eb70098dd06672 model (ready).
#> DLL: C:\Users\fidlema3\AppData\Local\Temp\1\RTMPAA~2\rx_00518f252742ae4507eb70098dd06672_x64_.rxd/rx_00518f252742ae4507eb70098dd06672_x64.dll
#> -- User supplied parameters: ---------------------------------------------- 
#>       Ton    tGamma eta.gamma 
#>        NA        NA        NA 
#> -- User initial conditions: ----------------------------------------------- 
#> named numeric(0)
#> -- Compartments: ---------------------------------------------------------- 
#> No ODEs in this DLL.
#> 
#> Calculated Variables:
#> [1] "gma"
#> ____________________________ RxODE Model Syntax ___________________________ 
#> if(t>=Ton){
#> gma=exp(tGamma+eta.gamma);
#> }
#> else{
#> gma=0;
#> }
#>  
#> ___________________________________________________________________________
```

<sup>Created on 2019-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by paolacarrillob** [comment]
Hi Matt,

thank you for the reply. However, I still cannot get it to work.
This is my code:

f1<-function(){
  ini({
    logTon = log(6) #time to start pupaeting (day)
    logGma = log(0.3) #growth rate (individual/day)
    logDelta = log(0.3) #death rate (individual/day)
    logH = log(150) #density-denpendent effect; number of individuals at
which the growth rate is half (individual)

    eta.Ton~1 ## BSV Ton
    eta.gma~1 ## BSV gamma
    eta.delta~1 ## BSV  delta
    eta.h~1 ## BSV h

    add.error<-0.1
  })
  model({
    Ton<-exp(logTon +eta.Ton)
    h<-exp(logH +eta.h)
    delta<-exp(logDelta+eta.delta)
    gma<-exp(logGma + eta.gma)
    #if (t >= Ton){ gma <- exp(logGma + eta.gma) } else { gma <- 0 }

    #initialize compartments
    L(0) = 100;
    #define ODEs
    d/dt(L) =-delta*L - gma*L*(1-L/(L+h));
    d/dt(P) = gma*L*(1-L/(L+h));
    P~add(add.error)
  })
}
Without the if statement, the model runs fine, and if I call nlmixr(f1) I
obtain the correct output:
▂▂ RxODE-based ODE model ▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂
── Initialization: ────────────────────────────────────────────────────────
Fixed Effects ($theta):
   logTon    logGma  logDelta      logH
 1.791759 -1.203973 -1.203973  5.010635

Omega ($omega):
          eta.Ton eta.gma eta.delta eta.h
eta.Ton         1       0         0     0
eta.gma         0       1         0     0
eta.delta       0       0         1     0
eta.h           0       0         0     1
── Model: ─────────────────────────────────────────────────────────────────
    Ton<-exp(logTon +eta.Ton)
    h<-exp(logH +eta.h)
    delta<-exp(logDelta+eta.delta)
    gma<-exp(logGma + eta.gma)
    #if (t >= Ton){ gma <- exp(logGamma + eta.gamma) } else { gma <- 0 }

    #initialize compartments
    L(0) = 100;
    #define ODEs
    d/dt(L) =-delta*L - gma*L*(1-L/(L+h));
    d/dt(P) = gma*L*(1-L/(L+h));
    P~add(add.error)
▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂


However, if I run the if-statement

1<-function(){
  ini({
    logTon = log(6) #time to start pupaeting (day)
    logGma = log(0.3) #growth rate (individual/day)
    logDelta = log(0.3) #death rate (individual/day)
    logH = log(150) #density-denpendent effect; number of individuals at
which the growth rate is half (individual)

    eta.Ton~1 ## BSV Ton
    eta.gma~1 ## BSV gamma
    eta.delta~1 ## BSV  delta
    eta.h~1 ## BSV h

    add.error<-0.1
  })
  model({
    Ton<-exp(logTon +eta.Ton)
    h<-exp(logH +eta.h)
    delta<-exp(logDelta+eta.delta)
    if (t >= Ton){ gma <- exp(logGma + eta.gma) } else { gma <- 0 }

    #initialize compartments
    L(0) = 100;
    #define ODEs
    d/dt(L) =-delta*L - gma*L*(1-L/(L+h));
    d/dt(P) = gma*L*(1-L/(L+h));
    P~add(add.error)
  })
}

I obtain the following error:
Error in parse(text = paste(c("function() {", rx.txt[1:w], "}"), collapse =
"\n")) :
  <text>:8:0: unexpected end of input
6:         gma <- exp(logGma + eta.gma)
7: }

I do not know what I am missing here.
------------------------------------------------------
Paola Carrillo-Bustamante, PhD
Schönhauser Allee 152
D-10435 Berlin
Germany

**Comment by mattfidler** [comment]
I can reproduce the issue;  RxODE doesn't have the issue, though

``` r
library(RxODE)

tmp <- RxODE({
Ton<-exp(logTon +eta.Ton)
h<-exp(logH +eta.h)
delta<-exp(logDelta+eta.delta)
gma<-exp(logGma + eta.gma)
if (t >= Ton){ gma <- exp(logGma + eta.gma) } else { gma <- 0 }

#initialize compartments
L(0) = 100;
#define ODEs
d/dt(L) =-delta*L - gma*L*(1-L/(L+h));
d/dt(P) = gma*L*(1-L/(L+h))
})

print(tmp)
#> RxODE 0.9.0-4 model named rx_3ceb163bc687e641e3f3ea419dea9139 model (ready).
#> $state: L, P
#> $params: logTon, eta.Ton, logH, eta.h, logDelta, eta.delta, logGma, eta.gma
#> $lhs: Ton, h, delta, gma
```

<sup>Created on 2019-04-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
Corrected in development version
