### ISSUE TITLE
wd doing strange things with paths?

### ISSUE THREAD

**Issue by timwaterhouse** [nlmixrdevelopment/RxODE#56]
Is the `wd` option supposed to be relative to the current directory?  That sort of seems to be the behaviour I'm seeing under Mac and Linux (although it repeats the current dir if no `wd` is specified).  If so, is there a way to specify an absolute path instead?

The following code compiles the model twice, when the current directory is `/Users/tim/Documents/work/RxODE_wd_test`.

``` r
library(RxODE)
ode <- " d/dt(test) = 0; "
m1 <- RxODE(model = ode, modName = "m1")
m1 <- RxODE(model = ode, modName = "m1", wd = "/private/tmp")
```

<sup>Created on 2018-11-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I would expect `m1.d` to be created under the current directory and `/private/tmp`, but they end up under `/Users/tim/Documents/work/RxODE_wd_test/Users/tim/Documents/work/RxODE_wd_test` for the first example (that's not a typo, the full path is repeated) and `/Users/tim/Documents/work/RxODE_wd_test/private/tmp` for the second.

Models run fine either way, but I'd like to be able to store the model files in a location other than somewhere under the current directory.

**Comment by mattfidler** [comment]
I think this fix will work for Mac/Linux paths.  Could you check.

To update:
```R
install.packages("devtools")
devtools::install_github("nlmixrdevelopment/RxODE")
```

**Comment by timwaterhouse** [comment]
Thank you, Matt! That actually didn't work for me so I tried to track down the error. I think I've found it in `rxCompile` so I've just made a pull request.  I don't use GitHub a lot, so please forgive me if I've made a mess with that.

**Comment by mattfidler** [comment]
Thanks Tim!  I merged the pull request.

**Comment by mattfidler** [comment]
On Linux (for me) this makes the "relative" path not so relative...

**Comment by mattfidler** [comment]
Perhaps this is a new issue.
