### ISSUE TITLE
RxODE doesn't know how to translate 'max' to SymPy. 

### ISSUE THREAD

**Issue by mayerbry** [nlmixrdevelopment/RxODE#57]
Does the nlmixr RxODE python parser support maximum or minimum functions? Potentially related to https://github.com/nlmixrdevelopment/RxODE/issues/54 as I cannot get if/else implementations to work either but that would be a solution. For context, I'm trying to fit a cut point which involves comparing it to the `t` input variable.

Happy to try to concoct a simple example if that would help, but want to confirm if this is a known limitation first. Thanks!

**Comment by mattfidler** [comment]
The `if`/`else` clauses should be able to work.  If you have an example where it doesn't work, it would be a bug.

```R
if (t < inp){
// change the model in some way
} else {
 // change the model in another way
}
```

The things that don't work yet in `RxODE` are:

```R
x = max(a,b)
x = min(a, b)
if (a<b){
} else if (b < c){
}
x = ifelse(a < b, c, d)
```

**Comment by mayerbry** [comment]
Below is an example using an adjusted version of the tutorial model that produces the following error:
```
Error in foceiFitCpp_(.ret) : 
  The following parameter(s) are required for solving: T0 
```

```
library(nlmixr)

f <- function(){
     ini({
         lCl <- 1.6      #log Cl (L/hr)
         lVc <- log(90)  #log Vc (L)
         lKA <- 0.1      #log Ka (1/hr)
         lt = c(1, 2, 3) # log time variable
         prop.err <- c(0, 0.2, 1)
         eta.Cl ~ 0.1 ## BSV Cl
         eta.Vc ~ 0.1 ## BSV Vc
         eta.KA ~ 0.1 ## BSV Ka
         eta.t0 ~ 0.1
     })
     model({
         Cl <- exp(lCl + eta.Cl)
         Vc <- exp(lVc + eta.Vc)
         KA <- exp(lKA + eta.KA)
         T0 <- exp(lt + eta.t0)

         if(t > T0){
           kel <- Cl / Vc
         }
         else{
           kel <- 2 * Cl / Vc
         }
         d/dt(depot)    = -KA*depot;
         d/dt(centr)  =  KA*depot-kel*centr;
         cp = centr / Vc;
         cp ~ prop(prop.err)
     })
}

d <- Oral_1CPT
d <- d[,names(d) != "SS"];
d <- nmDataConvert(d);

fit <- nlmixr(f, d, est="focei", control = foceiControl(print=50))
```

I also tried something like `time_adj = t- T0` then `if(time_adj > 0)` and I get the same error except: `The following parameter(s) are required for solving: time_adj`

**Comment by mattfidler** [comment]
Thank you for the example.  Let me look into it.

**Comment by mattfidler** [comment]
This should be fixed if you use the github version of RxODE

**Comment by mayerbry** [comment]
Installed the new `nlmixrdvelopment/RxODE and now I'm getting a new error:
`Error in regexpr("^/") : argument "text" is missing, with no default`

**Comment by mattfidler** [comment]
My oversight.  Thats what happens when I don't use a mac/linux regularly.

**Comment by mayerbry** [comment]
working now, thanks! However, one thing I noticed is that if you do `nlmixr(f)`, part of the output message states:
```
Covariates or Uninitialized Parameters ($all.covs)
[1] "T0"
```

**Comment by mattfidler** [comment]
This means that the covariate parsing for nlmixr is inaccurate.  It will not affect any of the `FO` methods or `nlme` method but may affect the `SAEM` method.  I have opend a nlmixr ticket for this related issue.

**Comment by mattfidler** [comment]
I also added max/min to the extra conditional statements.
