### ISSUE TITLE
Strange things with paths on Linux

### ISSUE THREAD

**Issue by mattfidler** [nlmixrdevelopment/RxODE#60]
See Issue #56 

Example:

```R
ode.1c <- RxODE("
C2 = center/V;
d/dt(center) = - CL*C2;
","ode1c")
```

This creates a directory "home/user/.../" depending where you are in the filesystem tree.

**Comment by timwaterhouse** [comment]
Do you mean your working directory is somewhere other than /home/user/...?  I've only tested that example in macOS, but when my working directory is /private/tmp, the files are saved in /private/tmp/ode1c.d.

**Comment by mattfidler** [comment]
If I start my R session in say `/home/matt/src/RxODE/R` it creates the model in the directory `/home/matt/src/RxODE/R/home/matt/src/RxODE/R/ode1c.d` when it should be just `/home/matt/src/RxODE/R/ode1c.d`

**Comment by mattfidler** [comment]
I think this was because I didn't pull your request.  Thank you for your help.

**Comment by timwaterhouse** [comment]
Ah, that makes sense. Because that was exactly the behaviour I was seeing before.
