### ISSUE TITLE
rxCompile shows output on console

### ISSUE THREAD

**Issue by rfaelens** [nlmixrdevelopment/RxODE#65]
I am using RxODE to execute automated tests. Every time a compilation takes place, the output of R CMD SHLIB pollutes my console.

The reason is that RxODE uses `system()` with default argument `show.output.on.console=TRUE`. It may be interesting to deactivate this by default, or modify it through the use of an option.

https://github.com/nlmixrdevelopment/RxODE/blob/441dec0ca84befc12f9cf1a6b17e0f7213439955/R/RxODE.R#L1324

**Comment by mattfidler** [comment]
I have started to use `sys` in the development branch starting on 37a6a25dd71ab5d178e3c504c7054729eff7e722 ;  It should probably address this issue. See #64

**Comment by rfaelens** [comment]
That should work, great!
Thanks.
