### ISSUE TITLE
v0.8.0-9 was not tagged

### ISSUE THREAD

**Issue by rfaelens** [nlmixrdevelopment/RxODE#68]
On December 10th 2018, RxODE v0.8.0-9 was released on CRAN.
The version bump to v0.8.1 occurred in https://github.com/nlmixrdevelopment/RxODE/commit/58a99abe01289b4e44e9e04d00bd6ec99ae5b514#diff-35ba4a2677442e210c23a00a5601aba3

So I guess v0.8.0-9 is this one? https://github.com/nlmixrdevelopment/RxODE/commit/2a1a7f6d461a9166c280cdaa45289dbcd1c2c62f

**Comment by mattfidler** [comment]
It isn't actually in github.  

All that was changed was removing comments from the `Makevars` otherwise CRAN would have removed us from there.

**Comment by mattfidler** [comment]
See 

https://github.com/cran/RxODE/commit/6fa35e374d700aff2e1bae7323e78437979838b5
