### ISSUE TITLE
Error in installation?

### ISSUE THREAD

**Issue by palar359** [nlmixrdevelopment/RxODE#70]
Hi,
I am getting the error message after successfully installing "devtools":
Error in library("devtools", lib = "C:/Rlib") : 
  no library trees found in 'lib.loc'

Can  anyone help to get through this?

thanks
Arindam Pal
PhD student 
University of Otago

**Comment by mattfidler** [comment]
Hi Aridam,

I have not seen this myself.  Since you are on windows, it may be easier to use the nlmixr installer, located here:

https://github.com/nlmixrdevelopment/nlmixr/releases

**Comment by mattfidler** [comment]
nlmixr R includes RxODE.
