### ISSUE TITLE
RxODE version 0.8.1-0 from github seems have a little problem working with nlmixr

### ISSUE THREAD

**Issue by DedeLLL** [nlmixrdevelopment/RxODE#78]
Hi,
Thanks for the great effort on the useful packages-- nlmixr and RxODE. I installed the latest version of RxODE (0.8.1-0) from Github both on Win10 and macos mojave. However, every time I tried to run the model, both systems returned the error: 
`Error in inDL(x, as.logical(local), as.logical(now), ...) : 
  unable to load shared object 'C:/Users/......./......./saem24944ef59a6x64.dll':`
 I removed the package and reinstalled the second latest version 0.8.0-9 from Cran and everything seemed to be back to normal again.  Did anyone encounter the same issue?

**Comment by mattfidler** [comment]
HI @DedeLLL 

If you use the RxODE version on github you need to use the nlmixr version on github.  The interface between SAEM and FOCEi and RxODE have changed to support the new events:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html

**Comment by mattfidler** [comment]
There are other (breaking) changes in nlmixr too including different objective function values for nlme (to more closely match NONMEM's FOCEi objective function value) and log likelihood adjustment for FOCEi, to give the correct likelihood [by correcting based on the number of observations times some factor (log(2*pi) if I remebere correctly)].

**Comment by DedeLLL** [comment]
> HI @DedeLLL
> 
> If you use the RxODE version on github you need to use the nlmixr version on github. The interface between SAEM and FOCEi and RxODE have changed to support the new events:
> 
> https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-events.html

Thanks a lot, Dr filder, It worked. The RxODE version 0.8.1.0 need to cooperate with nlmixr version 1.0.0.8 from github. By the way, a little reminding for those interested, installing nlmixr version 1.0.0.8 needs to install RxODE version 0.8.1.0 first or you may got an error in the compilation process during installing.

**Comment by DedeLLL** [comment]
> There are other (breaking) changes in nlmixr too including different objective function values for nlme (to more closely match NONMEM's FOCEi objective function value) and log likelihood adjustment for FOCEi, to give the correct likelihood [by correcting based on the number of observations times some factor (log(2*pi) if I remember correctly)].

Definitely thanks for the great work, such a powerful package deserving to be explored. 👍

**Comment by mattfidler** [comment]
Thank you @DedeLLL .  I'm glad you got it working!
