### ISSUE TITLE
How to save the compiled model for the use in other packages

### ISSUE THREAD

**Issue by zhenglei-gao** [nlmixrdevelopment/RxODE#80]
Maybe this is a stupid question and maybe this is the wrong place to ask, but I am not sure if I can save the compiled ODE functions and use them in other R sessions or include them into another package that is being developed. For example, a simple ODE like the one below. 

Thanks in advance for help. 

```
GUTS_SD_ode <- RxODE({
  Csi(0) = 0;
  H(0) = 0;
  d/dt(Csi) = kd*(Cw-Csi);
  d/dt(H) = kk*max(Csi-z,0)+hb;
  })

inits <- c(0,0)


ev <- eventTable(amount.units='mg', time.units='hours')
ev$add.sampling(1:tmax)
```

**Comment by mattfidler** [comment]
This is the correct place to post, I believe.

To help answer the question, are you planning on directly using RxODE compiled ODEs in C/C++ in your package?

Do you want to use the ODEs directly in your package by compiling them once before install?

**Comment by zhenglei-gao** [comment]
> This is the correct place to post, I believe.
> To help answer the question, are you planning on directly using RxODE compiled ODEs in C/C++ in your package?
> Do you want to use the ODEs directly in your package by compiling them once before install?

The package is intended to be distributed to my colleagues to use. I would like it to be compiled once during the installation of the package and then there is no need for re-compile it when my colleague is calling functions that make use of the compiled ODEs. 

Thank you very much for your help!

**Comment by mattfidler** [comment]
Since the compile is platform dependant it should be doable. 

I will try to make a model library  in RxODE to show an example of how it can work.

**Comment by zhenglei-gao** [comment]
> Since the compile is platform dependant it should be doable.
> I will try to make a model library  in RxODE to show an example of how it can work.

Great!

**Comment by mattfidler** [comment]
I have started the model library;  

Here is an example of one of the pre-compiled models in RxODE

``` r
library(RxODE)
oral1cmt %>% solve(et(amt=100) %>% et(id=1:4),omega=matrix(0.2,dimnames=list("bsvCl","bsvCl"))) %>% plot
#> Warning in rxSolve_(object, rxControl(..., events = events, params =
#> params), : Adding observations, for more control use et/add.sampling.
```

![](https://i.imgur.com/rqxdu6u.png)

<sup>Created on 2019-04-12 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
The process in not 100% worked out but part of it involves creating the model, and saving the model as a dataset/dll:

Here is where this is done in RxODE now:

https://github.com/nlmixrdevelopment/RxODE/blob/c94d231b435b2d174e70dd8faaa0a3eae02f0ae7/R/modlib.R#L21

The key is:
- Creating the RxODE model using `package="pkg"` and `modName=modelName`.  (Should create rx models under inst/rx/*.dll)
- Save the R model object in the data directory;  The easiest way to do this is: `usethis::use_data(compiledModel)`
- Install and load the package.  The "data"-sets should be the RxODE compiled models.

**Comment by mattfidler** [comment]
Ok. I have made it a bit simpler.  Lets say you have a model, first compile it:

```R
example6 <- RxODE("
a = 6
b = 0.6
d/dt(intestine) = -a*intestine
d/dt(blood)     = a*intestine - b*blood
")
```

Then you would save it in your package, similar to use-data, that is:
```R
RxODE::rxUse(example6)
```
To make sure the binary files exist on the platform you are using and they match the version of RxODE that is installed, please do the following:

```R
RxODE::rxUse()
```
Then you can do:

```R
devtools::install()
```

Then when you load your package you will see:

``` r
library(rxModels)
library(RxODE)
print(Jones2013)
#> RxODE 0.9.0-3 model named rxModels_Jones2013 model (unloaded reload with RxODE::rxLoad).
#> $state: Aad, Abo, Abr, Agu, Ahe, Aki, Ali, Alu, Amu, Ask, Asp, Ate, Ave, Aar, Are, D
#> $params: BW, FVad, FVbo, FVbr, FVgu, FVhe, FVki, FVli, FVlu, FVmu, FVsk, FVsp, FVte, FVve, FVar, FVpl, FVrb, FVre, FQad, FQbo, FQbr, FQgu, FQhe, FQki, FQh, FQlu, FQmu, FQsk, FQsp, FQte, FQre, Kpad, Kpbo, Kpbr, Kpgu, Kphe, Kpki, Kpli, Kplu, Kpmu, Kpsk, Kpsp, Kpte, Kpre, fup, BP, fumic, HLM_CLint, CLrenal, Ka, F, CO, MPPGL
#> $lhs: Cp

Jones2013 %>% solve(et(amt=10,cmt=D)) %>% plot
#> Warning in rxSolve_(object, rxControl(..., events = events, params =
#> params), : Adding observations, for more control use et/add.sampling.
```

![](https://i.imgur.com/lhnF1ef.png)

``` r

print(Jones2013)
#> RxODE 0.9.0-3 model named rxModels_Jones2013 model (ready).
#> $state: Aad, Abo, Abr, Agu, Ahe, Aki, Ali, Alu, Amu, Ask, Asp, Ate, Ave, Aar, Are, D
#> $params: BW, FVad, FVbo, FVbr, FVgu, FVhe, FVki, FVli, FVlu, FVmu, FVsk, FVsp, FVte, FVve, FVar, FVpl, FVrb, FVre, FQad, FQbo, FQbr, FQgu, FQhe, FQki, FQh, FQlu, FQmu, FQsk, FQsp, FQte, FQre, Kpad, Kpbo, Kpbr, Kpgu, Kphe, Kpki, Kpli, Kplu, Kpmu, Kpsk, Kpsp, Kpte, Kpre, fup, BP, fumic, HLM_CLint, CLrenal, Ka, F, CO, MPPGL
#> $lhs: Cp
```

<sup>Created on 2019-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by mattfidler** [comment]
I haven't figured out how to make the package call `RxODE::rxUse()` when installing.  That is the last missing piece.  Then you could simply do `devtools::install()` and everything would work great.

**Comment by mattfidler** [comment]
The example package is at https://github.com/nlmixrdevelopment/rxModels

**Comment by mattfidler** [comment]
Also note if you want to proved x64 and i386 binaries in your package you must run:

```R
RxODE::rxUse()
```
on each platform.

**Comment by mattfidler** [comment]
After testing, it works on windows, but not on linux.  I will have to give this more thought.

**Comment by mattfidler** [comment]
I have changed the interface.  It is described here:

https://nlmixrdevelopment.github.io/RxODE/articles/RxODE-rxUse.html

Let me know if it works for you.

**Comment by mattfidler** [comment]
I will assume this works for you.

If not, let me know.
