### ISSUE TITLE
Test failure with dev version of tibble

### ISSUE THREAD

**Issue by krlmlr** [nlmixrdevelopment/RxODE#9]
Tests seem to rely on output, which has changed slightly because we're now using pillar to format the columns: https://github.com/tidyverse/tibble/blob/e5ae87aaaf6a2643d66073193196f5061041bdfd/revdep/problems.md#rxode

Relying on output produced by other packages feels brittle. Can you please adapt the test to avoid checking the exact formatting of a tibble output?

**Comment by mattfidler** [comment]
Will I need to push this to cran for you as well?

**Comment by krlmlr** [comment]
Yes, please. It's easier if you release before I update tibble, but CRAN seems to be fine with a tibble release if the downstream maintainers are aware of the problem.

**Comment by mattfidler** [comment]
Don't wait for me to push a fix;  I will, but I'm a bit stuck with something right now.

**Comment by mattfidler** [comment]
This *should* be fixed by this commit.
